// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Adressen generated by hbm2java
 */
public class Adressen implements java.io.Serializable {

	private int id;
	private Integer nummer;
	private Date angelegtAm;
	private Date letzteÄnderung;
	private Boolean gesperrt;
	private Date geburtsDatum;
	private String persönlicheAnrede;
	private String kommentar;
	private Boolean aktiverSchüler;
	private Boolean actionFlag;
	private String dokumentenOrdner;
	private Integer geschlecht;
	private String kontakte;
	private String betreff;
	private Short graduierung;
	private Boolean nichtAktuell;
	private String kürzel;
	private Integer sortierung;
	private Double abschlag;
	private Boolean betrag;
	private Set adressgruppenverweises = new HashSet(0);
	private Set verbindungens = new HashSet(0);
	private Set adressaktionens = new HashSet(0);
	private Set rechnungens = new HashSet(0);
	private Set instrumentenverweises = new HashSet(0);
	private Set buchungens = new HashSet(0);
	private Set interessenverweises = new HashSet(0);
	private Set unterrichtsvertraeges = new HashSet(0);
	private Set bankverbindungens = new HashSet(0);
	private Set schulabschlussverweises = new HashSet(0);
	private Set lehrerkürzels = new HashSet(0);
	private Set staatsverweises = new HashSet(0);
	private Set anschriftens = new HashSet(0);
	private Set briefes = new HashSet(0);
	private Set kurslehrerverweises = new HashSet(0);

	public Adressen() {
	}

	public Adressen(int id) {
		this.id = id;
	}

	public Adressen(int id, Integer nummer, Date angelegtAm,
			Date letzteÄnderung, Boolean gesperrt, Date geburtsDatum,
			String persönlicheAnrede, String kommentar, Boolean aktiverSchüler,
			Boolean actionFlag, String dokumentenOrdner, Integer geschlecht,
			String kontakte, String betreff, Short graduierung,
			Boolean nichtAktuell, String kürzel, Integer sortierung,
			Double abschlag, Boolean betrag, Set adressgruppenverweises,
			Set verbindungens, Set adressaktionens, Set rechnungens,
			Set instrumentenverweises, Set buchungens, Set interessenverweises,
			Set unterrichtsvertraeges, Set bankverbindungens,
			Set schulabschlussverweises, Set lehrerkürzels,
			Set staatsverweises, Set anschriftens, Set briefes,
			Set kurslehrerverweises) {
		this.id = id;
		this.nummer = nummer;
		this.angelegtAm = angelegtAm;
		this.letzteÄnderung = letzteÄnderung;
		this.gesperrt = gesperrt;
		this.geburtsDatum = geburtsDatum;
		this.persönlicheAnrede = persönlicheAnrede;
		this.kommentar = kommentar;
		this.aktiverSchüler = aktiverSchüler;
		this.actionFlag = actionFlag;
		this.dokumentenOrdner = dokumentenOrdner;
		this.geschlecht = geschlecht;
		this.kontakte = kontakte;
		this.betreff = betreff;
		this.graduierung = graduierung;
		this.nichtAktuell = nichtAktuell;
		this.kürzel = kürzel;
		this.sortierung = sortierung;
		this.abschlag = abschlag;
		this.betrag = betrag;
		this.adressgruppenverweises = adressgruppenverweises;
		this.verbindungens = verbindungens;
		this.adressaktionens = adressaktionens;
		this.rechnungens = rechnungens;
		this.instrumentenverweises = instrumentenverweises;
		this.buchungens = buchungens;
		this.interessenverweises = interessenverweises;
		this.unterrichtsvertraeges = unterrichtsvertraeges;
		this.bankverbindungens = bankverbindungens;
		this.schulabschlussverweises = schulabschlussverweises;
		this.lehrerkürzels = lehrerkürzels;
		this.staatsverweises = staatsverweises;
		this.anschriftens = anschriftens;
		this.briefes = briefes;
		this.kurslehrerverweises = kurslehrerverweises;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getNummer() {
		return this.nummer;
	}

	public void setNummer(Integer nummer) {
		this.nummer = nummer;
	}

	public Date getAngelegtAm() {
		return this.angelegtAm;
	}

	public void setAngelegtAm(Date angelegtAm) {
		this.angelegtAm = angelegtAm;
	}

	public Date getLetzteÄnderung() {
		return this.letzteÄnderung;
	}

	public void setLetzteÄnderung(Date letzteÄnderung) {
		this.letzteÄnderung = letzteÄnderung;
	}

	public Boolean getGesperrt() {
		return this.gesperrt;
	}

	public void setGesperrt(Boolean gesperrt) {
		this.gesperrt = gesperrt;
	}

	public Date getGeburtsDatum() {
		return this.geburtsDatum;
	}

	public void setGeburtsDatum(Date geburtsDatum) {
		this.geburtsDatum = geburtsDatum;
	}

	public String getPersönlicheAnrede() {
		return this.persönlicheAnrede;
	}

	public void setPersönlicheAnrede(String persönlicheAnrede) {
		this.persönlicheAnrede = persönlicheAnrede;
	}

	public String getKommentar() {
		return this.kommentar;
	}

	public void setKommentar(String kommentar) {
		this.kommentar = kommentar;
	}

	public Boolean getAktiverSchüler() {
		return this.aktiverSchüler;
	}

	public void setAktiverSchüler(Boolean aktiverSchüler) {
		this.aktiverSchüler = aktiverSchüler;
	}

	public Boolean getActionFlag() {
		return this.actionFlag;
	}

	public void setActionFlag(Boolean actionFlag) {
		this.actionFlag = actionFlag;
	}

	public String getDokumentenOrdner() {
		return this.dokumentenOrdner;
	}

	public void setDokumentenOrdner(String dokumentenOrdner) {
		this.dokumentenOrdner = dokumentenOrdner;
	}

	public Integer getGeschlecht() {
		return this.geschlecht;
	}

	public void setGeschlecht(Integer geschlecht) {
		this.geschlecht = geschlecht;
	}

	public String getKontakte() {
		return this.kontakte;
	}

	public void setKontakte(String kontakte) {
		this.kontakte = kontakte;
	}

	public String getBetreff() {
		return this.betreff;
	}

	public void setBetreff(String betreff) {
		this.betreff = betreff;
	}

	public Short getGraduierung() {
		return this.graduierung;
	}

	public void setGraduierung(Short graduierung) {
		this.graduierung = graduierung;
	}

	public Boolean getNichtAktuell() {
		return this.nichtAktuell;
	}

	public void setNichtAktuell(Boolean nichtAktuell) {
		this.nichtAktuell = nichtAktuell;
	}

	public String getKürzel() {
		return this.kürzel;
	}

	public void setKürzel(String kürzel) {
		this.kürzel = kürzel;
	}

	public Integer getSortierung() {
		return this.sortierung;
	}

	public void setSortierung(Integer sortierung) {
		this.sortierung = sortierung;
	}

	public Double getAbschlag() {
		return this.abschlag;
	}

	public void setAbschlag(Double abschlag) {
		this.abschlag = abschlag;
	}

	public Boolean getBetrag() {
		return this.betrag;
	}

	public void setBetrag(Boolean betrag) {
		this.betrag = betrag;
	}

	public Set getAdressgruppenverweises() {
		return this.adressgruppenverweises;
	}

	public void setAdressgruppenverweises(Set adressgruppenverweises) {
		this.adressgruppenverweises = adressgruppenverweises;
	}

	public Set getVerbindungens() {
		return this.verbindungens;
	}

	public void setVerbindungens(Set verbindungens) {
		this.verbindungens = verbindungens;
	}

	public Set getAdressaktionens() {
		return this.adressaktionens;
	}

	public void setAdressaktionens(Set adressaktionens) {
		this.adressaktionens = adressaktionens;
	}

	public Set getRechnungens() {
		return this.rechnungens;
	}

	public void setRechnungens(Set rechnungens) {
		this.rechnungens = rechnungens;
	}

	public Set getInstrumentenverweises() {
		return this.instrumentenverweises;
	}

	public void setInstrumentenverweises(Set instrumentenverweises) {
		this.instrumentenverweises = instrumentenverweises;
	}

	public Set getBuchungens() {
		return this.buchungens;
	}

	public void setBuchungens(Set buchungens) {
		this.buchungens = buchungens;
	}

	public Set getInteressenverweises() {
		return this.interessenverweises;
	}

	public void setInteressenverweises(Set interessenverweises) {
		this.interessenverweises = interessenverweises;
	}

	public Set getUnterrichtsvertraeges() {
		return this.unterrichtsvertraeges;
	}

	public void setUnterrichtsvertraeges(Set unterrichtsvertraeges) {
		this.unterrichtsvertraeges = unterrichtsvertraeges;
	}

	public Set getBankverbindungens() {
		return this.bankverbindungens;
	}

	public void setBankverbindungens(Set bankverbindungens) {
		this.bankverbindungens = bankverbindungens;
	}

	public Set getSchulabschlussverweises() {
		return this.schulabschlussverweises;
	}

	public void setSchulabschlussverweises(Set schulabschlussverweises) {
		this.schulabschlussverweises = schulabschlussverweises;
	}

	public Set getLehrerkürzels() {
		return this.lehrerkürzels;
	}

	public void setLehrerkürzels(Set lehrerkürzels) {
		this.lehrerkürzels = lehrerkürzels;
	}

	public Set getStaatsverweises() {
		return this.staatsverweises;
	}

	public void setStaatsverweises(Set staatsverweises) {
		this.staatsverweises = staatsverweises;
	}

	public Set getAnschriftens() {
		return this.anschriftens;
	}

	public void setAnschriftens(Set anschriftens) {
		this.anschriftens = anschriftens;
	}

	public Set getBriefes() {
		return this.briefes;
	}

	public void setBriefes(Set briefes) {
		this.briefes = briefes;
	}

	public Set getKurslehrerverweises() {
		return this.kurslehrerverweises;
	}

	public void setKurslehrerverweises(Set kurslehrerverweises) {
		this.kurslehrerverweises = kurslehrerverweises;
	}

}
