// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Adressaktionenverweise generated by hbm2java
 */
public class Adressaktionenverweise implements java.io.Serializable {

	private AdressaktionenverweiseId id;

	public Adressaktionenverweise() {
	}

	public Adressaktionenverweise(AdressaktionenverweiseId id) {
		this.id = id;
	}

	public AdressaktionenverweiseId getId() {
		return this.id;
	}

	public void setId(AdressaktionenverweiseId id) {
		this.id = id;
	}

}
