// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Adressaktionen generated by hbm2java
 */
public class Adressaktionen implements java.io.Serializable {

	private int id;
	private Adressen adressen;
	private String text;
	private Date datum;
	private String bearbeiter;
	private Integer art;
	private Integer aktionId;

	public Adressaktionen() {
	}

	public Adressaktionen(int id) {
		this.id = id;
	}

	public Adressaktionen(int id, Adressen adressen, String text, Date datum,
			String bearbeiter, Integer art, Integer aktionId) {
		this.id = id;
		this.adressen = adressen;
		this.text = text;
		this.datum = datum;
		this.bearbeiter = bearbeiter;
		this.art = art;
		this.aktionId = aktionId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Adressen getAdressen() {
		return this.adressen;
	}

	public void setAdressen(Adressen adressen) {
		this.adressen = adressen;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	public String getBearbeiter() {
		return this.bearbeiter;
	}

	public void setBearbeiter(String bearbeiter) {
		this.bearbeiter = bearbeiter;
	}

	public Integer getArt() {
		return this.art;
	}

	public void setArt(Integer art) {
		this.art = art;
	}

	public Integer getAktionId() {
		return this.aktionId;
	}

	public void setAktionId(Integer aktionId) {
		this.aktionId = aktionId;
	}

}
