// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Adressgruppen generated by hbm2java
 */
public class Adressgruppen implements java.io.Serializable {

	private int id;
	private String name;
	private Boolean geschützt;
	private Boolean schüler;
	private Boolean student;

	public Adressgruppen() {
	}

	public Adressgruppen(int id) {
		this.id = id;
	}

	public Adressgruppen(int id, String name, Boolean geschützt,
			Boolean schüler, Boolean student) {
		this.id = id;
		this.name = name;
		this.geschützt = geschützt;
		this.schüler = schüler;
		this.student = student;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getGeschützt() {
		return this.geschützt;
	}

	public void setGeschützt(Boolean geschützt) {
		this.geschützt = geschützt;
	}

	public Boolean getSchüler() {
		return this.schüler;
	}

	public void setSchüler(Boolean schüler) {
		this.schüler = schüler;
	}

	public Boolean getStudent() {
		return this.student;
	}

	public void setStudent(Boolean student) {
		this.student = student;
	}

}
