// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Adressverbindungen generated by hbm2java
 */
public class Adressverbindungen implements java.io.Serializable {

	private int id;
	private String mobil;
	private String email;

	public Adressverbindungen() {
	}

	public Adressverbindungen(int id) {
		this.id = id;
	}

	public Adressverbindungen(int id, String mobil, String email) {
		this.id = id;
		this.mobil = mobil;
		this.email = email;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getMobil() {
		return this.mobil;
	}

	public void setMobil(String mobil) {
		this.mobil = mobil;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
