// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Aktionen generated by hbm2java
 */
public class Aktionen implements java.io.Serializable {

	private int id;
	private String name;
	private Boolean geschützt;
	private String text;
	private Date datum;
	private String bearbeiter;
	private Integer art;
	private Boolean gelöscht;
	private Set briefes = new HashSet(0);

	public Aktionen() {
	}

	public Aktionen(int id) {
		this.id = id;
	}

	public Aktionen(int id, String name, Boolean geschützt, String text,
			Date datum, String bearbeiter, Integer art, Boolean gelöscht,
			Set briefes) {
		this.id = id;
		this.name = name;
		this.geschützt = geschützt;
		this.text = text;
		this.datum = datum;
		this.bearbeiter = bearbeiter;
		this.art = art;
		this.gelöscht = gelöscht;
		this.briefes = briefes;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getGeschützt() {
		return this.geschützt;
	}

	public void setGeschützt(Boolean geschützt) {
		this.geschützt = geschützt;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	public String getBearbeiter() {
		return this.bearbeiter;
	}

	public void setBearbeiter(String bearbeiter) {
		this.bearbeiter = bearbeiter;
	}

	public Integer getArt() {
		return this.art;
	}

	public void setArt(Integer art) {
		this.art = art;
	}

	public Boolean getGelöscht() {
		return this.gelöscht;
	}

	public void setGelöscht(Boolean gelöscht) {
		this.gelöscht = gelöscht;
	}

	public Set getBriefes() {
		return this.briefes;
	}

	public void setBriefes(Set briefes) {
		this.briefes = briefes;
	}

}
