// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Anschriften generated by hbm2java
 */
public class Anschriften implements java.io.Serializable {

	private int id;
	private Adressen adressen;
	private String anschriftenName;
	private String anrede;
	private String firma;
	private String vorname;
	private String nachname;
	private String co;
	private String straße;
	private String plz;
	private String ort;
	private String länderkürzel;
	private String land;
	private Short nummer;
	private Date letzteÄnderung;
	private Boolean gesperrt;
	private String name;
	private Short hnr;

	public Anschriften() {
	}

	public Anschriften(int id) {
		this.id = id;
	}

	public Anschriften(int id, Adressen adressen, String anschriftenName,
			String anrede, String firma, String vorname, String nachname,
			String co, String straße, String plz, String ort,
			String länderkürzel, String land, Short nummer,
			Date letzteÄnderung, Boolean gesperrt, String name, Short hnr) {
		this.id = id;
		this.adressen = adressen;
		this.anschriftenName = anschriftenName;
		this.anrede = anrede;
		this.firma = firma;
		this.vorname = vorname;
		this.nachname = nachname;
		this.co = co;
		this.straße = straße;
		this.plz = plz;
		this.ort = ort;
		this.länderkürzel = länderkürzel;
		this.land = land;
		this.nummer = nummer;
		this.letzteÄnderung = letzteÄnderung;
		this.gesperrt = gesperrt;
		this.name = name;
		this.hnr = hnr;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Adressen getAdressen() {
		return this.adressen;
	}

	public void setAdressen(Adressen adressen) {
		this.adressen = adressen;
	}

	public String getAnschriftenName() {
		return this.anschriftenName;
	}

	public void setAnschriftenName(String anschriftenName) {
		this.anschriftenName = anschriftenName;
	}

	public String getAnrede() {
		return this.anrede;
	}

	public void setAnrede(String anrede) {
		this.anrede = anrede;
	}

	public String getFirma() {
		return this.firma;
	}

	public void setFirma(String firma) {
		this.firma = firma;
	}

	public String getVorname() {
		return this.vorname;
	}

	public void setVorname(String vorname) {
		this.vorname = vorname;
	}

	public String getNachname() {
		return this.nachname;
	}

	public void setNachname(String nachname) {
		this.nachname = nachname;
	}

	public String getCo() {
		return this.co;
	}

	public void setCo(String co) {
		this.co = co;
	}

	public String getStraße() {
		return this.straße;
	}

	public void setStraße(String straße) {
		this.straße = straße;
	}

	public String getPlz() {
		return this.plz;
	}

	public void setPlz(String plz) {
		this.plz = plz;
	}

	public String getOrt() {
		return this.ort;
	}

	public void setOrt(String ort) {
		this.ort = ort;
	}

	public String getLänderkürzel() {
		return this.länderkürzel;
	}

	public void setLänderkürzel(String länderkürzel) {
		this.länderkürzel = länderkürzel;
	}

	public String getLand() {
		return this.land;
	}

	public void setLand(String land) {
		this.land = land;
	}

	public Short getNummer() {
		return this.nummer;
	}

	public void setNummer(Short nummer) {
		this.nummer = nummer;
	}

	public Date getLetzteÄnderung() {
		return this.letzteÄnderung;
	}

	public void setLetzteÄnderung(Date letzteÄnderung) {
		this.letzteÄnderung = letzteÄnderung;
	}

	public Boolean getGesperrt() {
		return this.gesperrt;
	}

	public void setGesperrt(Boolean gesperrt) {
		this.gesperrt = gesperrt;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Short getHnr() {
		return this.hnr;
	}

	public void setHnr(Short hnr) {
		this.hnr = hnr;
	}

}
