// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Bankeinzugauswertung generated by hbm2java
 */
public class Bankeinzugauswertung implements java.io.Serializable {

	private BankeinzugauswertungId id;

	public Bankeinzugauswertung() {
	}

	public Bankeinzugauswertung(BankeinzugauswertungId id) {
		this.id = id;
	}

	public BankeinzugauswertungId getId() {
		return this.id;
	}

	public void setId(BankeinzugauswertungId id) {
		this.id = id;
	}

}
