// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * BankeinzugauswertungId generated by hbm2java
 */
public class BankeinzugauswertungId implements java.io.Serializable {

	private Double gebühr;
	private String kurs;
	private String adressGruppe;

	public BankeinzugauswertungId() {
	}

	public BankeinzugauswertungId(Double gebühr, String kurs,
			String adressGruppe) {
		this.gebühr = gebühr;
		this.kurs = kurs;
		this.adressGruppe = adressGruppe;
	}

	public Double getGebühr() {
		return this.gebühr;
	}

	public void setGebühr(Double gebühr) {
		this.gebühr = gebühr;
	}

	public String getKurs() {
		return this.kurs;
	}

	public void setKurs(String kurs) {
		this.kurs = kurs;
	}

	public String getAdressGruppe() {
		return this.adressGruppe;
	}

	public void setAdressGruppe(String adressGruppe) {
		this.adressGruppe = adressGruppe;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BankeinzugauswertungId))
			return false;
		BankeinzugauswertungId castOther = (BankeinzugauswertungId) other;

		return ((this.getGebühr() == castOther.getGebühr()) || (this
				.getGebühr() != null && castOther.getGebühr() != null && this
				.getGebühr().equals(castOther.getGebühr())))
				&& ((this.getKurs() == castOther.getKurs()) || (this.getKurs() != null
						&& castOther.getKurs() != null && this.getKurs()
						.equals(castOther.getKurs())))
				&& ((this.getAdressGruppe() == castOther.getAdressGruppe()) || (this
						.getAdressGruppe() != null
						&& castOther.getAdressGruppe() != null && this
						.getAdressGruppe().equals(castOther.getAdressGruppe())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGebühr() == null ? 0 : this.getGebühr().hashCode());
		result = 37 * result
				+ (getKurs() == null ? 0 : this.getKurs().hashCode());
		result = 37
				* result
				+ (getAdressGruppe() == null ? 0 : this.getAdressGruppe()
						.hashCode());
		return result;
	}

}
