// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Briefe generated by hbm2java
 */
public class Briefe implements java.io.Serializable {

	private int id;
	private Adressen adressen;
	private Aktionen aktionen;
	private Boolean gesperrt;
	private Date letzteÄnderung;
	private Date angelegtAm;
	private Date datum;
	private String bearbeiter;
	private Double status;
	private String text1;
	private Short anschrift;
	private String anrede;
	private String betrifft;
	private String anlagen;
	private String servus;
	private String nummer;
	private Short typ;
	private String namederAktion;
	private Boolean vorname;
	private Boolean nachname;

	public Briefe() {
	}

	public Briefe(int id) {
		this.id = id;
	}

	public Briefe(int id, Adressen adressen, Aktionen aktionen,
			Boolean gesperrt, Date letzteÄnderung, Date angelegtAm, Date datum,
			String bearbeiter, Double status, String text1, Short anschrift,
			String anrede, String betrifft, String anlagen, String servus,
			String nummer, Short typ, String namederAktion, Boolean vorname,
			Boolean nachname) {
		this.id = id;
		this.adressen = adressen;
		this.aktionen = aktionen;
		this.gesperrt = gesperrt;
		this.letzteÄnderung = letzteÄnderung;
		this.angelegtAm = angelegtAm;
		this.datum = datum;
		this.bearbeiter = bearbeiter;
		this.status = status;
		this.text1 = text1;
		this.anschrift = anschrift;
		this.anrede = anrede;
		this.betrifft = betrifft;
		this.anlagen = anlagen;
		this.servus = servus;
		this.nummer = nummer;
		this.typ = typ;
		this.namederAktion = namederAktion;
		this.vorname = vorname;
		this.nachname = nachname;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Adressen getAdressen() {
		return this.adressen;
	}

	public void setAdressen(Adressen adressen) {
		this.adressen = adressen;
	}

	public Aktionen getAktionen() {
		return this.aktionen;
	}

	public void setAktionen(Aktionen aktionen) {
		this.aktionen = aktionen;
	}

	public Boolean getGesperrt() {
		return this.gesperrt;
	}

	public void setGesperrt(Boolean gesperrt) {
		this.gesperrt = gesperrt;
	}

	public Date getLetzteÄnderung() {
		return this.letzteÄnderung;
	}

	public void setLetzteÄnderung(Date letzteÄnderung) {
		this.letzteÄnderung = letzteÄnderung;
	}

	public Date getAngelegtAm() {
		return this.angelegtAm;
	}

	public void setAngelegtAm(Date angelegtAm) {
		this.angelegtAm = angelegtAm;
	}

	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	public String getBearbeiter() {
		return this.bearbeiter;
	}

	public void setBearbeiter(String bearbeiter) {
		this.bearbeiter = bearbeiter;
	}

	public Double getStatus() {
		return this.status;
	}

	public void setStatus(Double status) {
		this.status = status;
	}

	public String getText1() {
		return this.text1;
	}

	public void setText1(String text1) {
		this.text1 = text1;
	}

	public Short getAnschrift() {
		return this.anschrift;
	}

	public void setAnschrift(Short anschrift) {
		this.anschrift = anschrift;
	}

	public String getAnrede() {
		return this.anrede;
	}

	public void setAnrede(String anrede) {
		this.anrede = anrede;
	}

	public String getBetrifft() {
		return this.betrifft;
	}

	public void setBetrifft(String betrifft) {
		this.betrifft = betrifft;
	}

	public String getAnlagen() {
		return this.anlagen;
	}

	public void setAnlagen(String anlagen) {
		this.anlagen = anlagen;
	}

	public String getServus() {
		return this.servus;
	}

	public void setServus(String servus) {
		this.servus = servus;
	}

	public String getNummer() {
		return this.nummer;
	}

	public void setNummer(String nummer) {
		this.nummer = nummer;
	}

	public Short getTyp() {
		return this.typ;
	}

	public void setTyp(Short typ) {
		this.typ = typ;
	}

	public String getNamederAktion() {
		return this.namederAktion;
	}

	public void setNamederAktion(String namederAktion) {
		this.namederAktion = namederAktion;
	}

	public Boolean getVorname() {
		return this.vorname;
	}

	public void setVorname(Boolean vorname) {
		this.vorname = vorname;
	}

	public Boolean getNachname() {
		return this.nachname;
	}

	public void setNachname(Boolean nachname) {
		this.nachname = nachname;
	}

}
