// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Buchungengebührenverweise generated by hbm2java
 */
public class Buchungengebührenverweise implements java.io.Serializable {

	private int id;
	private Integer gebühr;
	private Integer buchung;
	private Double betrag;

	public Buchungengebührenverweise() {
	}

	public Buchungengebührenverweise(int id) {
		this.id = id;
	}

	public Buchungengebührenverweise(int id, Integer gebühr, Integer buchung,
			Double betrag) {
		this.id = id;
		this.gebühr = gebühr;
		this.buchung = buchung;
		this.betrag = betrag;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getGebühr() {
		return this.gebühr;
	}

	public void setGebühr(Integer gebühr) {
		this.gebühr = gebühr;
	}

	public Integer getBuchung() {
		return this.buchung;
	}

	public void setBuchung(Integer buchung) {
		this.buchung = buchung;
	}

	public Double getBetrag() {
		return this.betrag;
	}

	public void setBetrag(Double betrag) {
		this.betrag = betrag;
	}

}
