// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Buchungen generated by hbm2java
 */
public class Buchungen implements java.io.Serializable {

	private int id;
	private Adressen adressen;
	private Integer spezialId;
	private BigDecimal betrag;
	private Short typ;
	private String buchungsText;
	private String auszug;
	private boolean schwarz;
	private Date datum;
	private Date angelegtam;
	private Integer konto;

	public Buchungen() {
	}

	public Buchungen(int id, boolean schwarz) {
		this.id = id;
		this.schwarz = schwarz;
	}

	public Buchungen(int id, Adressen adressen, Integer spezialId,
			BigDecimal betrag, Short typ, String buchungsText, String auszug,
			boolean schwarz, Date datum, Date angelegtam, Integer konto) {
		this.id = id;
		this.adressen = adressen;
		this.spezialId = spezialId;
		this.betrag = betrag;
		this.typ = typ;
		this.buchungsText = buchungsText;
		this.auszug = auszug;
		this.schwarz = schwarz;
		this.datum = datum;
		this.angelegtam = angelegtam;
		this.konto = konto;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Adressen getAdressen() {
		return this.adressen;
	}

	public void setAdressen(Adressen adressen) {
		this.adressen = adressen;
	}

	public Integer getSpezialId() {
		return this.spezialId;
	}

	public void setSpezialId(Integer spezialId) {
		this.spezialId = spezialId;
	}

	public BigDecimal getBetrag() {
		return this.betrag;
	}

	public void setBetrag(BigDecimal betrag) {
		this.betrag = betrag;
	}

	public Short getTyp() {
		return this.typ;
	}

	public void setTyp(Short typ) {
		this.typ = typ;
	}

	public String getBuchungsText() {
		return this.buchungsText;
	}

	public void setBuchungsText(String buchungsText) {
		this.buchungsText = buchungsText;
	}

	public String getAuszug() {
		return this.auszug;
	}

	public void setAuszug(String auszug) {
		this.auszug = auszug;
	}

	public boolean isSchwarz() {
		return this.schwarz;
	}

	public void setSchwarz(boolean schwarz) {
		this.schwarz = schwarz;
	}

	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	public Date getAngelegtam() {
		return this.angelegtam;
	}

	public void setAngelegtam(Date angelegtam) {
		this.angelegtam = angelegtam;
	}

	public Integer getKonto() {
		return this.konto;
	}

	public void setKonto(Integer konto) {
		this.konto = konto;
	}

}
