// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Differenz generated by hbm2java
 */
public class Differenz implements java.io.Serializable {

	private DifferenzId id;

	public Differenz() {
	}

	public Differenz(DifferenzId id) {
		this.id = id;
	}

	public DifferenzId getId() {
		return this.id;
	}

	public void setId(DifferenzId id) {
		this.id = id;
	}

}
