// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * DifferenzId generated by hbm2java
 */
public class DifferenzId implements java.io.Serializable {

	private String schüler;
	private String zahlungsart;
	private Double soll;
	private Double haben;
	private Double differenz;

	public DifferenzId() {
	}

	public DifferenzId(String schüler, String zahlungsart, Double soll,
			Double haben, Double differenz) {
		this.schüler = schüler;
		this.zahlungsart = zahlungsart;
		this.soll = soll;
		this.haben = haben;
		this.differenz = differenz;
	}

	public String getSchüler() {
		return this.schüler;
	}

	public void setSchüler(String schüler) {
		this.schüler = schüler;
	}

	public String getZahlungsart() {
		return this.zahlungsart;
	}

	public void setZahlungsart(String zahlungsart) {
		this.zahlungsart = zahlungsart;
	}

	public Double getSoll() {
		return this.soll;
	}

	public void setSoll(Double soll) {
		this.soll = soll;
	}

	public Double getHaben() {
		return this.haben;
	}

	public void setHaben(Double haben) {
		this.haben = haben;
	}

	public Double getDifferenz() {
		return this.differenz;
	}

	public void setDifferenz(Double differenz) {
		this.differenz = differenz;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DifferenzId))
			return false;
		DifferenzId castOther = (DifferenzId) other;

		return ((this.getSchüler() == castOther.getSchüler()) || (this
				.getSchüler() != null && castOther.getSchüler() != null && this
				.getSchüler().equals(castOther.getSchüler())))
				&& ((this.getZahlungsart() == castOther.getZahlungsart()) || (this
						.getZahlungsart() != null
						&& castOther.getZahlungsart() != null && this
						.getZahlungsart().equals(castOther.getZahlungsart())))
				&& ((this.getSoll() == castOther.getSoll()) || (this.getSoll() != null
						&& castOther.getSoll() != null && this.getSoll()
						.equals(castOther.getSoll())))
				&& ((this.getHaben() == castOther.getHaben()) || (this
						.getHaben() != null && castOther.getHaben() != null && this
						.getHaben().equals(castOther.getHaben())))
				&& ((this.getDifferenz() == castOther.getDifferenz()) || (this
						.getDifferenz() != null
						&& castOther.getDifferenz() != null && this
						.getDifferenz().equals(castOther.getDifferenz())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSchüler() == null ? 0 : this.getSchüler().hashCode());
		result = 37
				* result
				+ (getZahlungsart() == null ? 0 : this.getZahlungsart()
						.hashCode());
		result = 37 * result
				+ (getSoll() == null ? 0 : this.getSoll().hashCode());
		result = 37 * result
				+ (getHaben() == null ? 0 : this.getHaben().hashCode());
		result = 37 * result
				+ (getDifferenz() == null ? 0 : this.getDifferenz().hashCode());
		return result;
	}

}
