// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * EinausId generated by hbm2java
 */
public class EinausId implements java.io.Serializable {

	private String kategorie;
	private Double summeVonSollEin;
	private Double summeVonIstEin;
	private Double summeVonSollAus;
	private Double summeVonIstAus;

	public EinausId() {
	}

	public EinausId(String kategorie, Double summeVonSollEin,
			Double summeVonIstEin, Double summeVonSollAus, Double summeVonIstAus) {
		this.kategorie = kategorie;
		this.summeVonSollEin = summeVonSollEin;
		this.summeVonIstEin = summeVonIstEin;
		this.summeVonSollAus = summeVonSollAus;
		this.summeVonIstAus = summeVonIstAus;
	}

	public String getKategorie() {
		return this.kategorie;
	}

	public void setKategorie(String kategorie) {
		this.kategorie = kategorie;
	}

	public Double getSummeVonSollEin() {
		return this.summeVonSollEin;
	}

	public void setSummeVonSollEin(Double summeVonSollEin) {
		this.summeVonSollEin = summeVonSollEin;
	}

	public Double getSummeVonIstEin() {
		return this.summeVonIstEin;
	}

	public void setSummeVonIstEin(Double summeVonIstEin) {
		this.summeVonIstEin = summeVonIstEin;
	}

	public Double getSummeVonSollAus() {
		return this.summeVonSollAus;
	}

	public void setSummeVonSollAus(Double summeVonSollAus) {
		this.summeVonSollAus = summeVonSollAus;
	}

	public Double getSummeVonIstAus() {
		return this.summeVonIstAus;
	}

	public void setSummeVonIstAus(Double summeVonIstAus) {
		this.summeVonIstAus = summeVonIstAus;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EinausId))
			return false;
		EinausId castOther = (EinausId) other;

		return ((this.getKategorie() == castOther.getKategorie()) || (this
				.getKategorie() != null && castOther.getKategorie() != null && this
				.getKategorie().equals(castOther.getKategorie())))
				&& ((this.getSummeVonSollEin() == castOther
						.getSummeVonSollEin()) || (this.getSummeVonSollEin() != null
						&& castOther.getSummeVonSollEin() != null && this
						.getSummeVonSollEin().equals(
								castOther.getSummeVonSollEin())))
				&& ((this.getSummeVonIstEin() == castOther.getSummeVonIstEin()) || (this
						.getSummeVonIstEin() != null
						&& castOther.getSummeVonIstEin() != null && this
						.getSummeVonIstEin().equals(
								castOther.getSummeVonIstEin())))
				&& ((this.getSummeVonSollAus() == castOther
						.getSummeVonSollAus()) || (this.getSummeVonSollAus() != null
						&& castOther.getSummeVonSollAus() != null && this
						.getSummeVonSollAus().equals(
								castOther.getSummeVonSollAus())))
				&& ((this.getSummeVonIstAus() == castOther.getSummeVonIstAus()) || (this
						.getSummeVonIstAus() != null
						&& castOther.getSummeVonIstAus() != null && this
						.getSummeVonIstAus().equals(
								castOther.getSummeVonIstAus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getKategorie() == null ? 0 : this.getKategorie().hashCode());
		result = 37
				* result
				+ (getSummeVonSollEin() == null ? 0 : this.getSummeVonSollEin()
						.hashCode());
		result = 37
				* result
				+ (getSummeVonIstEin() == null ? 0 : this.getSummeVonIstEin()
						.hashCode());
		result = 37
				* result
				+ (getSummeVonSollAus() == null ? 0 : this.getSummeVonSollAus()
						.hashCode());
		result = 37
				* result
				+ (getSummeVonIstAus() == null ? 0 : this.getSummeVonIstAus()
						.hashCode());
		return result;
	}

}
