// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Einaus generated by hbm2java
 */
public class Einaus implements java.io.Serializable {

	private EinausId id;

	public Einaus() {
	}

	public Einaus(EinausId id) {
		this.id = id;
	}

	public EinausId getId() {
		return this.id;
	}

	public void setId(EinausId id) {
		this.id = id;
	}

}
