// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * EingebuehrenId generated by hbm2java
 */
public class EingebuehrenId implements java.io.Serializable {

	private String kategoriee;
	private String bez;
	private Double soll;
	private Double ist;
	private String kurs;
	private String name;

	public EingebuehrenId() {
	}

	public EingebuehrenId(String kategoriee, String bez, Double soll,
			Double ist, String kurs, String name) {
		this.kategoriee = kategoriee;
		this.bez = bez;
		this.soll = soll;
		this.ist = ist;
		this.kurs = kurs;
		this.name = name;
	}

	public String getKategoriee() {
		return this.kategoriee;
	}

	public void setKategoriee(String kategoriee) {
		this.kategoriee = kategoriee;
	}

	public String getBez() {
		return this.bez;
	}

	public void setBez(String bez) {
		this.bez = bez;
	}

	public Double getSoll() {
		return this.soll;
	}

	public void setSoll(Double soll) {
		this.soll = soll;
	}

	public Double getIst() {
		return this.ist;
	}

	public void setIst(Double ist) {
		this.ist = ist;
	}

	public String getKurs() {
		return this.kurs;
	}

	public void setKurs(String kurs) {
		this.kurs = kurs;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EingebuehrenId))
			return false;
		EingebuehrenId castOther = (EingebuehrenId) other;

		return ((this.getKategoriee() == castOther.getKategoriee()) || (this
				.getKategoriee() != null && castOther.getKategoriee() != null && this
				.getKategoriee().equals(castOther.getKategoriee())))
				&& ((this.getBez() == castOther.getBez()) || (this.getBez() != null
						&& castOther.getBez() != null && this.getBez().equals(
						castOther.getBez())))
				&& ((this.getSoll() == castOther.getSoll()) || (this.getSoll() != null
						&& castOther.getSoll() != null && this.getSoll()
						.equals(castOther.getSoll())))
				&& ((this.getIst() == castOther.getIst()) || (this.getIst() != null
						&& castOther.getIst() != null && this.getIst().equals(
						castOther.getIst())))
				&& ((this.getKurs() == castOther.getKurs()) || (this.getKurs() != null
						&& castOther.getKurs() != null && this.getKurs()
						.equals(castOther.getKurs())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getKategoriee() == null ? 0 : this.getKategoriee()
						.hashCode());
		result = 37 * result
				+ (getBez() == null ? 0 : this.getBez().hashCode());
		result = 37 * result
				+ (getSoll() == null ? 0 : this.getSoll().hashCode());
		result = 37 * result
				+ (getIst() == null ? 0 : this.getIst().hashCode());
		result = 37 * result
				+ (getKurs() == null ? 0 : this.getKurs().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
