// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Eingebuehren generated by hbm2java
 */
public class Eingebuehren implements java.io.Serializable {

	private EingebuehrenId id;

	public Eingebuehren() {
	}

	public Eingebuehren(EingebuehrenId id) {
		this.id = id;
	}

	public EingebuehrenId getId() {
		return this.id;
	}

	public void setId(EingebuehrenId id) {
		this.id = id;
	}

}
