// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Exportvorschriften generated by hbm2java
 */
public class Exportvorschriften implements java.io.Serializable {

	private ExportvorschriftenId id;

	public Exportvorschriften() {
	}

	public Exportvorschriften(ExportvorschriftenId id) {
		this.id = id;
	}

	public ExportvorschriftenId getId() {
		return this.id;
	}

	public void setId(ExportvorschriftenId id) {
		this.id = id;
	}

}
