// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Fachbelegung generated by hbm2java
 */
public class Fachbelegung implements java.io.Serializable {

	private FachbelegungId id;

	public Fachbelegung() {
	}

	public Fachbelegung(FachbelegungId id) {
		this.id = id;
	}

	public FachbelegungId getId() {
		return this.id;
	}

	public void setId(FachbelegungId id) {
		this.id = id;
	}

}
