// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * FachbelegungId generated by hbm2java
 */
public class FachbelegungId implements java.io.Serializable {

	private String kategorie;
	private Integer anzahlVonId;
	private String name;
	private String instrument;

	public FachbelegungId() {
	}

	public FachbelegungId(String kategorie, Integer anzahlVonId, String name,
			String instrument) {
		this.kategorie = kategorie;
		this.anzahlVonId = anzahlVonId;
		this.name = name;
		this.instrument = instrument;
	}

	public String getKategorie() {
		return this.kategorie;
	}

	public void setKategorie(String kategorie) {
		this.kategorie = kategorie;
	}

	public Integer getAnzahlVonId() {
		return this.anzahlVonId;
	}

	public void setAnzahlVonId(Integer anzahlVonId) {
		this.anzahlVonId = anzahlVonId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getInstrument() {
		return this.instrument;
	}

	public void setInstrument(String instrument) {
		this.instrument = instrument;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FachbelegungId))
			return false;
		FachbelegungId castOther = (FachbelegungId) other;

		return ((this.getKategorie() == castOther.getKategorie()) || (this
				.getKategorie() != null && castOther.getKategorie() != null && this
				.getKategorie().equals(castOther.getKategorie())))
				&& ((this.getAnzahlVonId() == castOther.getAnzahlVonId()) || (this
						.getAnzahlVonId() != null
						&& castOther.getAnzahlVonId() != null && this
						.getAnzahlVonId().equals(castOther.getAnzahlVonId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getInstrument() == castOther.getInstrument()) || (this
						.getInstrument() != null
						&& castOther.getInstrument() != null && this
						.getInstrument().equals(castOther.getInstrument())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getKategorie() == null ? 0 : this.getKategorie().hashCode());
		result = 37
				* result
				+ (getAnzahlVonId() == null ? 0 : this.getAnzahlVonId()
						.hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37
				* result
				+ (getInstrument() == null ? 0 : this.getInstrument()
						.hashCode());
		return result;
	}

}
