// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * FilterId generated by hbm2java
 */
public class FilterId implements java.io.Serializable {

	private Integer id;
	private String kategorieen;
	private String nachname;
	private String gruppe;
	private String plz;
	private String ort;
	private String land;
	private Date geburtsdatumAb;
	private Date geburtsdatumBis;
	private String kommentar;
	private Short aktiverSchüler;
	private Integer typUnterricht;
	private String interessen;
	private String instrumente;
	private String aktionen;
	private String name;
	private String aktionen2;
	private String betreff;
	private Date erstKontaktVon;
	private Date erstKontaktBis;
	private String sqlzusatz;
	private Date historyVon;
	private String historyBis;
	private Short alterVon;
	private Short alterBis;
	private Short email;
	private String kontakte;
	private Boolean nichtAktuell;

	public FilterId() {
	}

	public FilterId(Integer id, String kategorieen, String nachname,
			String gruppe, String plz, String ort, String land,
			Date geburtsdatumAb, Date geburtsdatumBis, String kommentar,
			Short aktiverSchüler, Integer typUnterricht, String interessen,
			String instrumente, String aktionen, String name, String aktionen2,
			String betreff, Date erstKontaktVon, Date erstKontaktBis,
			String sqlzusatz, Date historyVon, String historyBis,
			Short alterVon, Short alterBis, Short email, String kontakte,
			Boolean nichtAktuell) {
		this.id = id;
		this.kategorieen = kategorieen;
		this.nachname = nachname;
		this.gruppe = gruppe;
		this.plz = plz;
		this.ort = ort;
		this.land = land;
		this.geburtsdatumAb = geburtsdatumAb;
		this.geburtsdatumBis = geburtsdatumBis;
		this.kommentar = kommentar;
		this.aktiverSchüler = aktiverSchüler;
		this.typUnterricht = typUnterricht;
		this.interessen = interessen;
		this.instrumente = instrumente;
		this.aktionen = aktionen;
		this.name = name;
		this.aktionen2 = aktionen2;
		this.betreff = betreff;
		this.erstKontaktVon = erstKontaktVon;
		this.erstKontaktBis = erstKontaktBis;
		this.sqlzusatz = sqlzusatz;
		this.historyVon = historyVon;
		this.historyBis = historyBis;
		this.alterVon = alterVon;
		this.alterBis = alterBis;
		this.email = email;
		this.kontakte = kontakte;
		this.nichtAktuell = nichtAktuell;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getKategorieen() {
		return this.kategorieen;
	}

	public void setKategorieen(String kategorieen) {
		this.kategorieen = kategorieen;
	}

	public String getNachname() {
		return this.nachname;
	}

	public void setNachname(String nachname) {
		this.nachname = nachname;
	}

	public String getGruppe() {
		return this.gruppe;
	}

	public void setGruppe(String gruppe) {
		this.gruppe = gruppe;
	}

	public String getPlz() {
		return this.plz;
	}

	public void setPlz(String plz) {
		this.plz = plz;
	}

	public String getOrt() {
		return this.ort;
	}

	public void setOrt(String ort) {
		this.ort = ort;
	}

	public String getLand() {
		return this.land;
	}

	public void setLand(String land) {
		this.land = land;
	}

	public Date getGeburtsdatumAb() {
		return this.geburtsdatumAb;
	}

	public void setGeburtsdatumAb(Date geburtsdatumAb) {
		this.geburtsdatumAb = geburtsdatumAb;
	}

	public Date getGeburtsdatumBis() {
		return this.geburtsdatumBis;
	}

	public void setGeburtsdatumBis(Date geburtsdatumBis) {
		this.geburtsdatumBis = geburtsdatumBis;
	}

	public String getKommentar() {
		return this.kommentar;
	}

	public void setKommentar(String kommentar) {
		this.kommentar = kommentar;
	}

	public Short getAktiverSchüler() {
		return this.aktiverSchüler;
	}

	public void setAktiverSchüler(Short aktiverSchüler) {
		this.aktiverSchüler = aktiverSchüler;
	}

	public Integer getTypUnterricht() {
		return this.typUnterricht;
	}

	public void setTypUnterricht(Integer typUnterricht) {
		this.typUnterricht = typUnterricht;
	}

	public String getInteressen() {
		return this.interessen;
	}

	public void setInteressen(String interessen) {
		this.interessen = interessen;
	}

	public String getInstrumente() {
		return this.instrumente;
	}

	public void setInstrumente(String instrumente) {
		this.instrumente = instrumente;
	}

	public String getAktionen() {
		return this.aktionen;
	}

	public void setAktionen(String aktionen) {
		this.aktionen = aktionen;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAktionen2() {
		return this.aktionen2;
	}

	public void setAktionen2(String aktionen2) {
		this.aktionen2 = aktionen2;
	}

	public String getBetreff() {
		return this.betreff;
	}

	public void setBetreff(String betreff) {
		this.betreff = betreff;
	}

	public Date getErstKontaktVon() {
		return this.erstKontaktVon;
	}

	public void setErstKontaktVon(Date erstKontaktVon) {
		this.erstKontaktVon = erstKontaktVon;
	}

	public Date getErstKontaktBis() {
		return this.erstKontaktBis;
	}

	public void setErstKontaktBis(Date erstKontaktBis) {
		this.erstKontaktBis = erstKontaktBis;
	}

	public String getSqlzusatz() {
		return this.sqlzusatz;
	}

	public void setSqlzusatz(String sqlzusatz) {
		this.sqlzusatz = sqlzusatz;
	}

	public Date getHistoryVon() {
		return this.historyVon;
	}

	public void setHistoryVon(Date historyVon) {
		this.historyVon = historyVon;
	}

	public String getHistoryBis() {
		return this.historyBis;
	}

	public void setHistoryBis(String historyBis) {
		this.historyBis = historyBis;
	}

	public Short getAlterVon() {
		return this.alterVon;
	}

	public void setAlterVon(Short alterVon) {
		this.alterVon = alterVon;
	}

	public Short getAlterBis() {
		return this.alterBis;
	}

	public void setAlterBis(Short alterBis) {
		this.alterBis = alterBis;
	}

	public Short getEmail() {
		return this.email;
	}

	public void setEmail(Short email) {
		this.email = email;
	}

	public String getKontakte() {
		return this.kontakte;
	}

	public void setKontakte(String kontakte) {
		this.kontakte = kontakte;
	}

	public Boolean getNichtAktuell() {
		return this.nichtAktuell;
	}

	public void setNichtAktuell(Boolean nichtAktuell) {
		this.nichtAktuell = nichtAktuell;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FilterId))
			return false;
		FilterId castOther = (FilterId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getKategorieen() == castOther.getKategorieen()) || (this
						.getKategorieen() != null
						&& castOther.getKategorieen() != null && this
						.getKategorieen().equals(castOther.getKategorieen())))
				&& ((this.getNachname() == castOther.getNachname()) || (this
						.getNachname() != null
						&& castOther.getNachname() != null && this
						.getNachname().equals(castOther.getNachname())))
				&& ((this.getGruppe() == castOther.getGruppe()) || (this
						.getGruppe() != null && castOther.getGruppe() != null && this
						.getGruppe().equals(castOther.getGruppe())))
				&& ((this.getPlz() == castOther.getPlz()) || (this.getPlz() != null
						&& castOther.getPlz() != null && this.getPlz().equals(
						castOther.getPlz())))
				&& ((this.getOrt() == castOther.getOrt()) || (this.getOrt() != null
						&& castOther.getOrt() != null && this.getOrt().equals(
						castOther.getOrt())))
				&& ((this.getLand() == castOther.getLand()) || (this.getLand() != null
						&& castOther.getLand() != null && this.getLand()
						.equals(castOther.getLand())))
				&& ((this.getGeburtsdatumAb() == castOther.getGeburtsdatumAb()) || (this
						.getGeburtsdatumAb() != null
						&& castOther.getGeburtsdatumAb() != null && this
						.getGeburtsdatumAb().equals(
								castOther.getGeburtsdatumAb())))
				&& ((this.getGeburtsdatumBis() == castOther
						.getGeburtsdatumBis()) || (this.getGeburtsdatumBis() != null
						&& castOther.getGeburtsdatumBis() != null && this
						.getGeburtsdatumBis().equals(
								castOther.getGeburtsdatumBis())))
				&& ((this.getKommentar() == castOther.getKommentar()) || (this
						.getKommentar() != null
						&& castOther.getKommentar() != null && this
						.getKommentar().equals(castOther.getKommentar())))
				&& ((this.getAktiverSchüler() == castOther.getAktiverSchüler()) || (this
						.getAktiverSchüler() != null
						&& castOther.getAktiverSchüler() != null && this
						.getAktiverSchüler().equals(
								castOther.getAktiverSchüler())))
				&& ((this.getTypUnterricht() == castOther.getTypUnterricht()) || (this
						.getTypUnterricht() != null
						&& castOther.getTypUnterricht() != null && this
						.getTypUnterricht()
						.equals(castOther.getTypUnterricht())))
				&& ((this.getInteressen() == castOther.getInteressen()) || (this
						.getInteressen() != null
						&& castOther.getInteressen() != null && this
						.getInteressen().equals(castOther.getInteressen())))
				&& ((this.getInstrumente() == castOther.getInstrumente()) || (this
						.getInstrumente() != null
						&& castOther.getInstrumente() != null && this
						.getInstrumente().equals(castOther.getInstrumente())))
				&& ((this.getAktionen() == castOther.getAktionen()) || (this
						.getAktionen() != null
						&& castOther.getAktionen() != null && this
						.getAktionen().equals(castOther.getAktionen())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getAktionen2() == castOther.getAktionen2()) || (this
						.getAktionen2() != null
						&& castOther.getAktionen2() != null && this
						.getAktionen2().equals(castOther.getAktionen2())))
				&& ((this.getBetreff() == castOther.getBetreff()) || (this
						.getBetreff() != null && castOther.getBetreff() != null && this
						.getBetreff().equals(castOther.getBetreff())))
				&& ((this.getErstKontaktVon() == castOther.getErstKontaktVon()) || (this
						.getErstKontaktVon() != null
						&& castOther.getErstKontaktVon() != null && this
						.getErstKontaktVon().equals(
								castOther.getErstKontaktVon())))
				&& ((this.getErstKontaktBis() == castOther.getErstKontaktBis()) || (this
						.getErstKontaktBis() != null
						&& castOther.getErstKontaktBis() != null && this
						.getErstKontaktBis().equals(
								castOther.getErstKontaktBis())))
				&& ((this.getSqlzusatz() == castOther.getSqlzusatz()) || (this
						.getSqlzusatz() != null
						&& castOther.getSqlzusatz() != null && this
						.getSqlzusatz().equals(castOther.getSqlzusatz())))
				&& ((this.getHistoryVon() == castOther.getHistoryVon()) || (this
						.getHistoryVon() != null
						&& castOther.getHistoryVon() != null && this
						.getHistoryVon().equals(castOther.getHistoryVon())))
				&& ((this.getHistoryBis() == castOther.getHistoryBis()) || (this
						.getHistoryBis() != null
						&& castOther.getHistoryBis() != null && this
						.getHistoryBis().equals(castOther.getHistoryBis())))
				&& ((this.getAlterVon() == castOther.getAlterVon()) || (this
						.getAlterVon() != null
						&& castOther.getAlterVon() != null && this
						.getAlterVon().equals(castOther.getAlterVon())))
				&& ((this.getAlterBis() == castOther.getAlterBis()) || (this
						.getAlterBis() != null
						&& castOther.getAlterBis() != null && this
						.getAlterBis().equals(castOther.getAlterBis())))
				&& ((this.getEmail() == castOther.getEmail()) || (this
						.getEmail() != null && castOther.getEmail() != null && this
						.getEmail().equals(castOther.getEmail())))
				&& ((this.getKontakte() == castOther.getKontakte()) || (this
						.getKontakte() != null
						&& castOther.getKontakte() != null && this
						.getKontakte().equals(castOther.getKontakte())))
				&& ((this.getNichtAktuell() == castOther.getNichtAktuell()) || (this
						.getNichtAktuell() != null
						&& castOther.getNichtAktuell() != null && this
						.getNichtAktuell().equals(castOther.getNichtAktuell())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getKategorieen() == null ? 0 : this.getKategorieen()
						.hashCode());
		result = 37 * result
				+ (getNachname() == null ? 0 : this.getNachname().hashCode());
		result = 37 * result
				+ (getGruppe() == null ? 0 : this.getGruppe().hashCode());
		result = 37 * result
				+ (getPlz() == null ? 0 : this.getPlz().hashCode());
		result = 37 * result
				+ (getOrt() == null ? 0 : this.getOrt().hashCode());
		result = 37 * result
				+ (getLand() == null ? 0 : this.getLand().hashCode());
		result = 37
				* result
				+ (getGeburtsdatumAb() == null ? 0 : this.getGeburtsdatumAb()
						.hashCode());
		result = 37
				* result
				+ (getGeburtsdatumBis() == null ? 0 : this.getGeburtsdatumBis()
						.hashCode());
		result = 37 * result
				+ (getKommentar() == null ? 0 : this.getKommentar().hashCode());
		result = 37
				* result
				+ (getAktiverSchüler() == null ? 0 : this.getAktiverSchüler()
						.hashCode());
		result = 37
				* result
				+ (getTypUnterricht() == null ? 0 : this.getTypUnterricht()
						.hashCode());
		result = 37
				* result
				+ (getInteressen() == null ? 0 : this.getInteressen()
						.hashCode());
		result = 37
				* result
				+ (getInstrumente() == null ? 0 : this.getInstrumente()
						.hashCode());
		result = 37 * result
				+ (getAktionen() == null ? 0 : this.getAktionen().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result
				+ (getAktionen2() == null ? 0 : this.getAktionen2().hashCode());
		result = 37 * result
				+ (getBetreff() == null ? 0 : this.getBetreff().hashCode());
		result = 37
				* result
				+ (getErstKontaktVon() == null ? 0 : this.getErstKontaktVon()
						.hashCode());
		result = 37
				* result
				+ (getErstKontaktBis() == null ? 0 : this.getErstKontaktBis()
						.hashCode());
		result = 37 * result
				+ (getSqlzusatz() == null ? 0 : this.getSqlzusatz().hashCode());
		result = 37
				* result
				+ (getHistoryVon() == null ? 0 : this.getHistoryVon()
						.hashCode());
		result = 37
				* result
				+ (getHistoryBis() == null ? 0 : this.getHistoryBis()
						.hashCode());
		result = 37 * result
				+ (getAlterVon() == null ? 0 : this.getAlterVon().hashCode());
		result = 37 * result
				+ (getAlterBis() == null ? 0 : this.getAlterBis().hashCode());
		result = 37 * result
				+ (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result
				+ (getKontakte() == null ? 0 : this.getKontakte().hashCode());
		result = 37
				* result
				+ (getNichtAktuell() == null ? 0 : this.getNichtAktuell()
						.hashCode());
		return result;
	}

}
