// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Filter generated by hbm2java
 */
public class Filter implements java.io.Serializable {

	private FilterId id;

	public Filter() {
	}

	public Filter(FilterId id) {
		this.id = id;
	}

	public FilterId getId() {
		return this.id;
	}

	public void setId(FilterId id) {
		this.id = id;
	}

}
