// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Gebuchtekurse generated by hbm2java
 */
public class Gebuchtekurse implements java.io.Serializable {

	private int id;
	private Kurse kurse;
	private Schülerinformationen schülerinformationen;
	private Date von;
	private Date bis;
	private String tage;
	private String uhrZeiten;
	private Date letzteÄnderung;
	private boolean gesperrt;
	private Date angelegtAm;
	private String rabatte;
	private boolean studienGebühr;
	private Short gruppe;
	private Integer kategorie;
	private Integer zahlungsart;
	private Integer zahlungsweise;
	private Integer ermässigt;

	public Gebuchtekurse() {
	}

	public Gebuchtekurse(int id, boolean gesperrt, boolean studienGebühr) {
		this.id = id;
		this.gesperrt = gesperrt;
		this.studienGebühr = studienGebühr;
	}

	public Gebuchtekurse(int id, Kurse kurse,
			Schülerinformationen schülerinformationen, Date von, Date bis,
			String tage, String uhrZeiten, Date letzteÄnderung,
			boolean gesperrt, Date angelegtAm, String rabatte,
			boolean studienGebühr, Short gruppe, Integer kategorie,
			Integer zahlungsart, Integer zahlungsweise, Integer ermässigt) {
		this.id = id;
		this.kurse = kurse;
		this.schülerinformationen = schülerinformationen;
		this.von = von;
		this.bis = bis;
		this.tage = tage;
		this.uhrZeiten = uhrZeiten;
		this.letzteÄnderung = letzteÄnderung;
		this.gesperrt = gesperrt;
		this.angelegtAm = angelegtAm;
		this.rabatte = rabatte;
		this.studienGebühr = studienGebühr;
		this.gruppe = gruppe;
		this.kategorie = kategorie;
		this.zahlungsart = zahlungsart;
		this.zahlungsweise = zahlungsweise;
		this.ermässigt = ermässigt;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Kurse getKurse() {
		return this.kurse;
	}

	public void setKurse(Kurse kurse) {
		this.kurse = kurse;
	}

	public Schülerinformationen getSchülerinformationen() {
		return this.schülerinformationen;
	}

	public void setSchülerinformationen(
			Schülerinformationen schülerinformationen) {
		this.schülerinformationen = schülerinformationen;
	}

	public Date getVon() {
		return this.von;
	}

	public void setVon(Date von) {
		this.von = von;
	}

	public Date getBis() {
		return this.bis;
	}

	public void setBis(Date bis) {
		this.bis = bis;
	}

	public String getTage() {
		return this.tage;
	}

	public void setTage(String tage) {
		this.tage = tage;
	}

	public String getUhrZeiten() {
		return this.uhrZeiten;
	}

	public void setUhrZeiten(String uhrZeiten) {
		this.uhrZeiten = uhrZeiten;
	}

	public Date getLetzteÄnderung() {
		return this.letzteÄnderung;
	}

	public void setLetzteÄnderung(Date letzteÄnderung) {
		this.letzteÄnderung = letzteÄnderung;
	}

	public boolean isGesperrt() {
		return this.gesperrt;
	}

	public void setGesperrt(boolean gesperrt) {
		this.gesperrt = gesperrt;
	}

	public Date getAngelegtAm() {
		return this.angelegtAm;
	}

	public void setAngelegtAm(Date angelegtAm) {
		this.angelegtAm = angelegtAm;
	}

	public String getRabatte() {
		return this.rabatte;
	}

	public void setRabatte(String rabatte) {
		this.rabatte = rabatte;
	}

	public boolean isStudienGebühr() {
		return this.studienGebühr;
	}

	public void setStudienGebühr(boolean studienGebühr) {
		this.studienGebühr = studienGebühr;
	}

	public Short getGruppe() {
		return this.gruppe;
	}

	public void setGruppe(Short gruppe) {
		this.gruppe = gruppe;
	}

	public Integer getKategorie() {
		return this.kategorie;
	}

	public void setKategorie(Integer kategorie) {
		this.kategorie = kategorie;
	}

	public Integer getZahlungsart() {
		return this.zahlungsart;
	}

	public void setZahlungsart(Integer zahlungsart) {
		this.zahlungsart = zahlungsart;
	}

	public Integer getZahlungsweise() {
		return this.zahlungsweise;
	}

	public void setZahlungsweise(Integer zahlungsweise) {
		this.zahlungsweise = zahlungsweise;
	}

	public Integer getErmässigt() {
		return this.ermässigt;
	}

	public void setErmässigt(Integer ermässigt) {
		this.ermässigt = ermässigt;
	}

}
