// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Gruppengebühren generated by hbm2java
 */
public class Gruppengebühren implements java.io.Serializable {

	private int id;
	private Kurse kurse;
	private Short anzahl;
	private Double gebühr;
	private Double honorar;
	private Double honorar2;
	private Integer minuten;
	private Boolean gelöscht;
	private Double honorar3;
	private Double gebührErmässigt;
	private Double gebührErmässigt2;

	public Gruppengebühren() {
	}

	public Gruppengebühren(int id) {
		this.id = id;
	}

	public Gruppengebühren(int id, Kurse kurse, Short anzahl, Double gebühr,
			Double honorar, Double honorar2, Integer minuten, Boolean gelöscht,
			Double honorar3, Double gebührErmässigt, Double gebührErmässigt2) {
		this.id = id;
		this.kurse = kurse;
		this.anzahl = anzahl;
		this.gebühr = gebühr;
		this.honorar = honorar;
		this.honorar2 = honorar2;
		this.minuten = minuten;
		this.gelöscht = gelöscht;
		this.honorar3 = honorar3;
		this.gebührErmässigt = gebührErmässigt;
		this.gebührErmässigt2 = gebührErmässigt2;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Kurse getKurse() {
		return this.kurse;
	}

	public void setKurse(Kurse kurse) {
		this.kurse = kurse;
	}

	public Short getAnzahl() {
		return this.anzahl;
	}

	public void setAnzahl(Short anzahl) {
		this.anzahl = anzahl;
	}

	public Double getGebühr() {
		return this.gebühr;
	}

	public void setGebühr(Double gebühr) {
		this.gebühr = gebühr;
	}

	public Double getHonorar() {
		return this.honorar;
	}

	public void setHonorar(Double honorar) {
		this.honorar = honorar;
	}

	public Double getHonorar2() {
		return this.honorar2;
	}

	public void setHonorar2(Double honorar2) {
		this.honorar2 = honorar2;
	}

	public Integer getMinuten() {
		return this.minuten;
	}

	public void setMinuten(Integer minuten) {
		this.minuten = minuten;
	}

	public Boolean getGelöscht() {
		return this.gelöscht;
	}

	public void setGelöscht(Boolean gelöscht) {
		this.gelöscht = gelöscht;
	}

	public Double getHonorar3() {
		return this.honorar3;
	}

	public void setHonorar3(Double honorar3) {
		this.honorar3 = honorar3;
	}

	public Double getGebührErmässigt() {
		return this.gebührErmässigt;
	}

	public void setGebührErmässigt(Double gebührErmässigt) {
		this.gebührErmässigt = gebührErmässigt;
	}

	public Double getGebührErmässigt2() {
		return this.gebührErmässigt2;
	}

	public void setGebührErmässigt2(Double gebührErmässigt2) {
		this.gebührErmässigt2 = gebührErmässigt2;
	}

}
