// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Honorare generated by hbm2java
 */
public class Honorare implements java.io.Serializable {

	private int id;
	private Kurse kurse;
	private Double honorar;
	private Integer lehrerId;
	private Date von;
	private Date bis;
	private Integer unterrichtId;
	private Double bezahlt;
	private Boolean fällig;
	private String bezeichnung;
	private Boolean einzelHonorar;
	private Boolean pauschalHonorar;
	private Integer kategorieId;
	private String datum;
	private String auszug;
	private Integer sonstHonorarId;
	private Short kursGruppe;
	private Boolean abschlag;

	public Honorare() {
	}

	public Honorare(int id) {
		this.id = id;
	}

	public Honorare(int id, Kurse kurse, Double honorar, Integer lehrerId,
			Date von, Date bis, Integer unterrichtId, Double bezahlt,
			Boolean fällig, String bezeichnung, Boolean einzelHonorar,
			Boolean pauschalHonorar, Integer kategorieId, String datum,
			String auszug, Integer sonstHonorarId, Short kursGruppe,
			Boolean abschlag) {
		this.id = id;
		this.kurse = kurse;
		this.honorar = honorar;
		this.lehrerId = lehrerId;
		this.von = von;
		this.bis = bis;
		this.unterrichtId = unterrichtId;
		this.bezahlt = bezahlt;
		this.fällig = fällig;
		this.bezeichnung = bezeichnung;
		this.einzelHonorar = einzelHonorar;
		this.pauschalHonorar = pauschalHonorar;
		this.kategorieId = kategorieId;
		this.datum = datum;
		this.auszug = auszug;
		this.sonstHonorarId = sonstHonorarId;
		this.kursGruppe = kursGruppe;
		this.abschlag = abschlag;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Kurse getKurse() {
		return this.kurse;
	}

	public void setKurse(Kurse kurse) {
		this.kurse = kurse;
	}

	public Double getHonorar() {
		return this.honorar;
	}

	public void setHonorar(Double honorar) {
		this.honorar = honorar;
	}

	public Integer getLehrerId() {
		return this.lehrerId;
	}

	public void setLehrerId(Integer lehrerId) {
		this.lehrerId = lehrerId;
	}

	public Date getVon() {
		return this.von;
	}

	public void setVon(Date von) {
		this.von = von;
	}

	public Date getBis() {
		return this.bis;
	}

	public void setBis(Date bis) {
		this.bis = bis;
	}

	public Integer getUnterrichtId() {
		return this.unterrichtId;
	}

	public void setUnterrichtId(Integer unterrichtId) {
		this.unterrichtId = unterrichtId;
	}

	public Double getBezahlt() {
		return this.bezahlt;
	}

	public void setBezahlt(Double bezahlt) {
		this.bezahlt = bezahlt;
	}

	public Boolean getFällig() {
		return this.fällig;
	}

	public void setFällig(Boolean fällig) {
		this.fällig = fällig;
	}

	public String getBezeichnung() {
		return this.bezeichnung;
	}

	public void setBezeichnung(String bezeichnung) {
		this.bezeichnung = bezeichnung;
	}

	public Boolean getEinzelHonorar() {
		return this.einzelHonorar;
	}

	public void setEinzelHonorar(Boolean einzelHonorar) {
		this.einzelHonorar = einzelHonorar;
	}

	public Boolean getPauschalHonorar() {
		return this.pauschalHonorar;
	}

	public void setPauschalHonorar(Boolean pauschalHonorar) {
		this.pauschalHonorar = pauschalHonorar;
	}

	public Integer getKategorieId() {
		return this.kategorieId;
	}

	public void setKategorieId(Integer kategorieId) {
		this.kategorieId = kategorieId;
	}

	public String getDatum() {
		return this.datum;
	}

	public void setDatum(String datum) {
		this.datum = datum;
	}

	public String getAuszug() {
		return this.auszug;
	}

	public void setAuszug(String auszug) {
		this.auszug = auszug;
	}

	public Integer getSonstHonorarId() {
		return this.sonstHonorarId;
	}

	public void setSonstHonorarId(Integer sonstHonorarId) {
		this.sonstHonorarId = sonstHonorarId;
	}

	public Short getKursGruppe() {
		return this.kursGruppe;
	}

	public void setKursGruppe(Short kursGruppe) {
		this.kursGruppe = kursGruppe;
	}

	public Boolean getAbschlag() {
		return this.abschlag;
	}

	public void setAbschlag(Boolean abschlag) {
		this.abschlag = abschlag;
	}

}
