// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Instrumente generated by hbm2java
 */
public class Instrumente implements java.io.Serializable {

	private int id;
	private String name;
	private Boolean geschützt;
	private String kürzel;

	public Instrumente() {
	}

	public Instrumente(int id) {
		this.id = id;
	}

	public Instrumente(int id, String name, Boolean geschützt, String kürzel) {
		this.id = id;
		this.name = name;
		this.geschützt = geschützt;
		this.kürzel = kürzel;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getGeschützt() {
		return this.geschützt;
	}

	public void setGeschützt(Boolean geschützt) {
		this.geschützt = geschützt;
	}

	public String getKürzel() {
		return this.kürzel;
	}

	public void setKürzel(String kürzel) {
		this.kürzel = kürzel;
	}

}
