// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Kategorien generated by hbm2java
 */
public class Kategorien implements java.io.Serializable {

	private int id;
	private String name;
	private Boolean geschützt;
	private Set sonstigehonorares = new HashSet(0);
	private Set gebührens = new HashSet(0);

	public Kategorien() {
	}

	public Kategorien(int id) {
		this.id = id;
	}

	public Kategorien(int id, String name, Boolean geschützt,
			Set sonstigehonorares, Set gebührens) {
		this.id = id;
		this.name = name;
		this.geschützt = geschützt;
		this.sonstigehonorares = sonstigehonorares;
		this.gebührens = gebührens;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getGeschützt() {
		return this.geschützt;
	}

	public void setGeschützt(Boolean geschützt) {
		this.geschützt = geschützt;
	}

	public Set getSonstigehonorares() {
		return this.sonstigehonorares;
	}

	public void setSonstigehonorares(Set sonstigehonorares) {
		this.sonstigehonorares = sonstigehonorares;
	}

	public Set getGebührens() {
		return this.gebührens;
	}

	public void setGebührens(Set gebührens) {
		this.gebührens = gebührens;
	}

}
