// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Kontakte generated by hbm2java
 */
public class Kontakte implements java.io.Serializable {

	private int id;
	private String text;

	public Kontakte() {
	}

	public Kontakte(int id) {
		this.id = id;
	}

	public Kontakte(int id, String text) {
		this.id = id;
		this.text = text;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}
