// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Konten generated by hbm2java
 */
public class Konten implements java.io.Serializable {

	private int id;
	private String name;
	private Boolean geschützt;

	public Konten() {
	}

	public Konten(int id) {
		this.id = id;
	}

	public Konten(int id, String name, Boolean geschützt) {
		this.id = id;
		this.name = name;
		this.geschützt = geschützt;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getGeschützt() {
		return this.geschützt;
	}

	public void setGeschützt(Boolean geschützt) {
		this.geschützt = geschützt;
	}

}
