// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Kurslehrerverweise generated by hbm2java
 */
public class Kurslehrerverweise implements java.io.Serializable {

	private KurslehrerverweiseId id;
	private Adressen adressen;

	public Kurslehrerverweise() {
	}

	public Kurslehrerverweise(KurslehrerverweiseId id) {
		this.id = id;
	}

	public Kurslehrerverweise(KurslehrerverweiseId id, Adressen adressen) {
		this.id = id;
		this.adressen = adressen;
	}

	public KurslehrerverweiseId getId() {
		return this.id;
	}

	public void setId(KurslehrerverweiseId id) {
		this.id = id;
	}

	public Adressen getAdressen() {
		return this.adressen;
	}

	public void setAdressen(Adressen adressen) {
		this.adressen = adressen;
	}

}
