// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * KurslehrerverweiseId generated by hbm2java
 */
public class KurslehrerverweiseId implements java.io.Serializable {

	private Integer id;
	private Integer adresseId;
	private Integer eigenschaftId;

	public KurslehrerverweiseId() {
	}

	public KurslehrerverweiseId(Integer id, Integer adresseId,
			Integer eigenschaftId) {
		this.id = id;
		this.adresseId = adresseId;
		this.eigenschaftId = eigenschaftId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getAdresseId() {
		return this.adresseId;
	}

	public void setAdresseId(Integer adresseId) {
		this.adresseId = adresseId;
	}

	public Integer getEigenschaftId() {
		return this.eigenschaftId;
	}

	public void setEigenschaftId(Integer eigenschaftId) {
		this.eigenschaftId = eigenschaftId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KurslehrerverweiseId))
			return false;
		KurslehrerverweiseId castOther = (KurslehrerverweiseId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getAdresseId() == castOther.getAdresseId()) || (this
						.getAdresseId() != null
						&& castOther.getAdresseId() != null && this
						.getAdresseId().equals(castOther.getAdresseId())))
				&& ((this.getEigenschaftId() == castOther.getEigenschaftId()) || (this
						.getEigenschaftId() != null
						&& castOther.getEigenschaftId() != null && this
						.getEigenschaftId()
						.equals(castOther.getEigenschaftId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getAdresseId() == null ? 0 : this.getAdresseId().hashCode());
		result = 37
				* result
				+ (getEigenschaftId() == null ? 0 : this.getEigenschaftId()
						.hashCode());
		return result;
	}

}
