// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Kursgruppen generated by hbm2java
 */
public class Kursgruppen implements java.io.Serializable {

	private int id;
	private Kurse kurse;
	private String bezeichnung;
	private Short gruppe;

	public Kursgruppen() {
	}

	public Kursgruppen(int id) {
		this.id = id;
	}

	public Kursgruppen(int id, Kurse kurse, String bezeichnung, Short gruppe) {
		this.id = id;
		this.kurse = kurse;
		this.bezeichnung = bezeichnung;
		this.gruppe = gruppe;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Kurse getKurse() {
		return this.kurse;
	}

	public void setKurse(Kurse kurse) {
		this.kurse = kurse;
	}

	public String getBezeichnung() {
		return this.bezeichnung;
	}

	public void setBezeichnung(String bezeichnung) {
		this.bezeichnung = bezeichnung;
	}

	public Short getGruppe() {
		return this.gruppe;
	}

	public void setGruppe(Short gruppe) {
		this.gruppe = gruppe;
	}

}
