// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Kurse generated by hbm2java
 */
public class Kurse implements java.io.Serializable {

	private int id;
	private Turnus turnus;
	private Date letzteÄnderung;
	private Date angelgtAm;
	private Boolean gesperrt;
	private String name;
	private Integer typ;
	private Double honorar;
	private Double gebühr;
	private String beschreibung;
	private String nummer;
	private Short anzahlProTurnus;
	private Short anzahlStunden;
	private Short minTeilnehmer;
	private Short maxTeilnehmer;
	private Integer instrument;
	private Date gültigBis;
	private String möglicheKategorieen;
	private Date von;
	private Date bis;
	private String möglicheRabatte;
	private Double studiumHonorar;
	private Short anzahlGruppen;
	private Integer tarifid;
	private Boolean abschlag;
	private Set honorares = new HashSet(0);
	private Set gruppengebührens = new HashSet(0);
	private Set gebuchtekurses = new HashSet(0);
	private Set gebührens = new HashSet(0);
	private Set verweildauers = new HashSet(0);
	private Set kursgruppens = new HashSet(0);

	public Kurse() {
	}

	public Kurse(int id) {
		this.id = id;
	}

	public Kurse(int id, Turnus turnus, Date letzteÄnderung, Date angelgtAm,
			Boolean gesperrt, String name, Integer typ, Double honorar,
			Double gebühr, String beschreibung, String nummer,
			Short anzahlProTurnus, Short anzahlStunden, Short minTeilnehmer,
			Short maxTeilnehmer, Integer instrument, Date gültigBis,
			String möglicheKategorieen, Date von, Date bis,
			String möglicheRabatte, Double studiumHonorar, Short anzahlGruppen,
			Integer tarifid, Boolean abschlag, Set honorares,
			Set gruppengebührens, Set gebuchtekurses, Set gebührens,
			Set verweildauers, Set kursgruppens) {
		this.id = id;
		this.turnus = turnus;
		this.letzteÄnderung = letzteÄnderung;
		this.angelgtAm = angelgtAm;
		this.gesperrt = gesperrt;
		this.name = name;
		this.typ = typ;
		this.honorar = honorar;
		this.gebühr = gebühr;
		this.beschreibung = beschreibung;
		this.nummer = nummer;
		this.anzahlProTurnus = anzahlProTurnus;
		this.anzahlStunden = anzahlStunden;
		this.minTeilnehmer = minTeilnehmer;
		this.maxTeilnehmer = maxTeilnehmer;
		this.instrument = instrument;
		this.gültigBis = gültigBis;
		this.möglicheKategorieen = möglicheKategorieen;
		this.von = von;
		this.bis = bis;
		this.möglicheRabatte = möglicheRabatte;
		this.studiumHonorar = studiumHonorar;
		this.anzahlGruppen = anzahlGruppen;
		this.tarifid = tarifid;
		this.abschlag = abschlag;
		this.honorares = honorares;
		this.gruppengebührens = gruppengebührens;
		this.gebuchtekurses = gebuchtekurses;
		this.gebührens = gebührens;
		this.verweildauers = verweildauers;
		this.kursgruppens = kursgruppens;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Turnus getTurnus() {
		return this.turnus;
	}

	public void setTurnus(Turnus turnus) {
		this.turnus = turnus;
	}

	public Date getLetzteÄnderung() {
		return this.letzteÄnderung;
	}

	public void setLetzteÄnderung(Date letzteÄnderung) {
		this.letzteÄnderung = letzteÄnderung;
	}

	public Date getAngelgtAm() {
		return this.angelgtAm;
	}

	public void setAngelgtAm(Date angelgtAm) {
		this.angelgtAm = angelgtAm;
	}

	public Boolean getGesperrt() {
		return this.gesperrt;
	}

	public void setGesperrt(Boolean gesperrt) {
		this.gesperrt = gesperrt;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getTyp() {
		return this.typ;
	}

	public void setTyp(Integer typ) {
		this.typ = typ;
	}

	public Double getHonorar() {
		return this.honorar;
	}

	public void setHonorar(Double honorar) {
		this.honorar = honorar;
	}

	public Double getGebühr() {
		return this.gebühr;
	}

	public void setGebühr(Double gebühr) {
		this.gebühr = gebühr;
	}

	public String getBeschreibung() {
		return this.beschreibung;
	}

	public void setBeschreibung(String beschreibung) {
		this.beschreibung = beschreibung;
	}

	public String getNummer() {
		return this.nummer;
	}

	public void setNummer(String nummer) {
		this.nummer = nummer;
	}

	public Short getAnzahlProTurnus() {
		return this.anzahlProTurnus;
	}

	public void setAnzahlProTurnus(Short anzahlProTurnus) {
		this.anzahlProTurnus = anzahlProTurnus;
	}

	public Short getAnzahlStunden() {
		return this.anzahlStunden;
	}

	public void setAnzahlStunden(Short anzahlStunden) {
		this.anzahlStunden = anzahlStunden;
	}

	public Short getMinTeilnehmer() {
		return this.minTeilnehmer;
	}

	public void setMinTeilnehmer(Short minTeilnehmer) {
		this.minTeilnehmer = minTeilnehmer;
	}

	public Short getMaxTeilnehmer() {
		return this.maxTeilnehmer;
	}

	public void setMaxTeilnehmer(Short maxTeilnehmer) {
		this.maxTeilnehmer = maxTeilnehmer;
	}

	public Integer getInstrument() {
		return this.instrument;
	}

	public void setInstrument(Integer instrument) {
		this.instrument = instrument;
	}

	public Date getGültigBis() {
		return this.gültigBis;
	}

	public void setGültigBis(Date gültigBis) {
		this.gültigBis = gültigBis;
	}

	public String getMöglicheKategorieen() {
		return this.möglicheKategorieen;
	}

	public void setMöglicheKategorieen(String möglicheKategorieen) {
		this.möglicheKategorieen = möglicheKategorieen;
	}

	public Date getVon() {
		return this.von;
	}

	public void setVon(Date von) {
		this.von = von;
	}

	public Date getBis() {
		return this.bis;
	}

	public void setBis(Date bis) {
		this.bis = bis;
	}

	public String getMöglicheRabatte() {
		return this.möglicheRabatte;
	}

	public void setMöglicheRabatte(String möglicheRabatte) {
		this.möglicheRabatte = möglicheRabatte;
	}

	public Double getStudiumHonorar() {
		return this.studiumHonorar;
	}

	public void setStudiumHonorar(Double studiumHonorar) {
		this.studiumHonorar = studiumHonorar;
	}

	public Short getAnzahlGruppen() {
		return this.anzahlGruppen;
	}

	public void setAnzahlGruppen(Short anzahlGruppen) {
		this.anzahlGruppen = anzahlGruppen;
	}

	public Integer getTarifid() {
		return this.tarifid;
	}

	public void setTarifid(Integer tarifid) {
		this.tarifid = tarifid;
	}

	public Boolean getAbschlag() {
		return this.abschlag;
	}

	public void setAbschlag(Boolean abschlag) {
		this.abschlag = abschlag;
	}

	public Set getHonorares() {
		return this.honorares;
	}

	public void setHonorares(Set honorares) {
		this.honorares = honorares;
	}

	public Set getGruppengebührens() {
		return this.gruppengebührens;
	}

	public void setGruppengebührens(Set gruppengebührens) {
		this.gruppengebührens = gruppengebührens;
	}

	public Set getGebuchtekurses() {
		return this.gebuchtekurses;
	}

	public void setGebuchtekurses(Set gebuchtekurses) {
		this.gebuchtekurses = gebuchtekurses;
	}

	public Set getGebührens() {
		return this.gebührens;
	}

	public void setGebührens(Set gebührens) {
		this.gebührens = gebührens;
	}

	public Set getVerweildauers() {
		return this.verweildauers;
	}

	public void setVerweildauers(Set verweildauers) {
		this.verweildauers = verweildauers;
	}

	public Set getKursgruppens() {
		return this.kursgruppens;
	}

	public void setKursgruppens(Set kursgruppens) {
		this.kursgruppens = kursgruppens;
	}

}
