// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Lehrerkürzel generated by hbm2java
 */
public class Lehrerkürzel implements java.io.Serializable {

	private LehrerkürzelId id;
	private Adressen adressen;

	public Lehrerkürzel() {
	}

	public Lehrerkürzel(LehrerkürzelId id) {
		this.id = id;
	}

	public Lehrerkürzel(LehrerkürzelId id, Adressen adressen) {
		this.id = id;
		this.adressen = adressen;
	}

	public LehrerkürzelId getId() {
		return this.id;
	}

	public void setId(LehrerkürzelId id) {
		this.id = id;
	}

	public Adressen getAdressen() {
		return this.adressen;
	}

	public void setAdressen(Adressen adressen) {
		this.adressen = adressen;
	}

}
