// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * LehrerkürzelId generated by hbm2java
 */
public class LehrerkürzelId implements java.io.Serializable {

	private Integer adresseId;
	private String lehrerKürzel;

	public LehrerkürzelId() {
	}

	public LehrerkürzelId(Integer adresseId, String lehrerKürzel) {
		this.adresseId = adresseId;
		this.lehrerKürzel = lehrerKürzel;
	}

	public Integer getAdresseId() {
		return this.adresseId;
	}

	public void setAdresseId(Integer adresseId) {
		this.adresseId = adresseId;
	}

	public String getLehrerKürzel() {
		return this.lehrerKürzel;
	}

	public void setLehrerKürzel(String lehrerKürzel) {
		this.lehrerKürzel = lehrerKürzel;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LehrerkürzelId))
			return false;
		LehrerkürzelId castOther = (LehrerkürzelId) other;

		return ((this.getAdresseId() == castOther.getAdresseId()) || (this
				.getAdresseId() != null && castOther.getAdresseId() != null && this
				.getAdresseId().equals(castOther.getAdresseId())))
				&& ((this.getLehrerKürzel() == castOther.getLehrerKürzel()) || (this
						.getLehrerKürzel() != null
						&& castOther.getLehrerKürzel() != null && this
						.getLehrerKürzel().equals(castOther.getLehrerKürzel())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAdresseId() == null ? 0 : this.getAdresseId().hashCode());
		result = 37
				* result
				+ (getLehrerKürzel() == null ? 0 : this.getLehrerKürzel()
						.hashCode());
		return result;
	}

}
