// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Rabatte generated by hbm2java
 */
public class Rabatte implements java.io.Serializable {

	private int id;
	private String name;
	private Float prozent;
	private Integer position;
	private String ausschluﬂ;
	private Boolean betrag;

	public Rabatte() {
	}

	public Rabatte(int id) {
		this.id = id;
	}

	public Rabatte(int id, String name, Float prozent, Integer position,
			String ausschluﬂ, Boolean betrag) {
		this.id = id;
		this.name = name;
		this.prozent = prozent;
		this.position = position;
		this.ausschluﬂ = ausschluﬂ;
		this.betrag = betrag;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Float getProzent() {
		return this.prozent;
	}

	public void setProzent(Float prozent) {
		this.prozent = prozent;
	}

	public Integer getPosition() {
		return this.position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}

	public String getAusschluﬂ() {
		return this.ausschluﬂ;
	}

	public void setAusschluﬂ(String ausschluﬂ) {
		this.ausschluﬂ = ausschluﬂ;
	}

	public Boolean getBetrag() {
		return this.betrag;
	}

	public void setBetrag(Boolean betrag) {
		this.betrag = betrag;
	}

}
