// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Rechnungen generated by hbm2java
 */
public class Rechnungen implements java.io.Serializable {

	private int id;
	private Adressen adressen;
	private String kommentar;
	private Date datum;
	private Double gesamtBrutto;
	private Float skonto;
	private Double skontiertBrutto;
	private Double bezahlt;
	private Date fälligAm;
	private Boolean skontoGewährt;
	private Boolean gedruckt;
	private String rabattString;
	private String rabattText;
	private Date fälligDatum;

	public Rechnungen() {
	}

	public Rechnungen(int id) {
		this.id = id;
	}

	public Rechnungen(int id, Adressen adressen, String kommentar, Date datum,
			Double gesamtBrutto, Float skonto, Double skontiertBrutto,
			Double bezahlt, Date fälligAm, Boolean skontoGewährt,
			Boolean gedruckt, String rabattString, String rabattText,
			Date fälligDatum) {
		this.id = id;
		this.adressen = adressen;
		this.kommentar = kommentar;
		this.datum = datum;
		this.gesamtBrutto = gesamtBrutto;
		this.skonto = skonto;
		this.skontiertBrutto = skontiertBrutto;
		this.bezahlt = bezahlt;
		this.fälligAm = fälligAm;
		this.skontoGewährt = skontoGewährt;
		this.gedruckt = gedruckt;
		this.rabattString = rabattString;
		this.rabattText = rabattText;
		this.fälligDatum = fälligDatum;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Adressen getAdressen() {
		return this.adressen;
	}

	public void setAdressen(Adressen adressen) {
		this.adressen = adressen;
	}

	public String getKommentar() {
		return this.kommentar;
	}

	public void setKommentar(String kommentar) {
		this.kommentar = kommentar;
	}

	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	public Double getGesamtBrutto() {
		return this.gesamtBrutto;
	}

	public void setGesamtBrutto(Double gesamtBrutto) {
		this.gesamtBrutto = gesamtBrutto;
	}

	public Float getSkonto() {
		return this.skonto;
	}

	public void setSkonto(Float skonto) {
		this.skonto = skonto;
	}

	public Double getSkontiertBrutto() {
		return this.skontiertBrutto;
	}

	public void setSkontiertBrutto(Double skontiertBrutto) {
		this.skontiertBrutto = skontiertBrutto;
	}

	public Double getBezahlt() {
		return this.bezahlt;
	}

	public void setBezahlt(Double bezahlt) {
		this.bezahlt = bezahlt;
	}

	public Date getFälligAm() {
		return this.fälligAm;
	}

	public void setFälligAm(Date fälligAm) {
		this.fälligAm = fälligAm;
	}

	public Boolean getSkontoGewährt() {
		return this.skontoGewährt;
	}

	public void setSkontoGewährt(Boolean skontoGewährt) {
		this.skontoGewährt = skontoGewährt;
	}

	public Boolean getGedruckt() {
		return this.gedruckt;
	}

	public void setGedruckt(Boolean gedruckt) {
		this.gedruckt = gedruckt;
	}

	public String getRabattString() {
		return this.rabattString;
	}

	public void setRabattString(String rabattString) {
		this.rabattString = rabattString;
	}

	public String getRabattText() {
		return this.rabattText;
	}

	public void setRabattText(String rabattText) {
		this.rabattText = rabattText;
	}

	public Date getFälligDatum() {
		return this.fälligDatum;
	}

	public void setFälligDatum(Date fälligDatum) {
		this.fälligDatum = fälligDatum;
	}

}
