// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Schülerinformationen generated by hbm2java
 */
public class Schülerinformationen implements java.io.Serializable {

	private int id;
	private Integer zahlungsArt;
	private Integer zahlungsWeise;
	private String wannBeZahlen;
	private Double studiengebühr;
	private Date studBeginn1;
	private Date studBeginn2;
	private Date studBeginn3;
	private Date vorStudBeginn1;
	private Date vorStudBeginn2;
	private String rabattstring;
	private Double bankeinzugAutomatik;
	private Double inaktiv;
	private Double studiengebühr2;
	private Double studiengebühr3;
	private Double vorStudiengebühr1;
	private Double vorStudiengebühr2;
	private Integer kategorieStud1;
	private Integer kategorieStud2;
	private Integer kategorieStud3;
	private Integer kategorieVorStud1;
	private Integer kategorieVorStud2;
	private Set gebuchtekurses = new HashSet(0);
	private Set verweildauers = new HashSet(0);
	private Set schülerinaktivzeitens = new HashSet(0);
	private Set gebührens = new HashSet(0);

	public Schülerinformationen() {
	}

	public Schülerinformationen(int id) {
		this.id = id;
	}

	public Schülerinformationen(int id, Integer zahlungsArt,
			Integer zahlungsWeise, String wannBeZahlen, Double studiengebühr,
			Date studBeginn1, Date studBeginn2, Date studBeginn3,
			Date vorStudBeginn1, Date vorStudBeginn2, String rabattstring,
			Double bankeinzugAutomatik, Double inaktiv, Double studiengebühr2,
			Double studiengebühr3, Double vorStudiengebühr1,
			Double vorStudiengebühr2, Integer kategorieStud1,
			Integer kategorieStud2, Integer kategorieStud3,
			Integer kategorieVorStud1, Integer kategorieVorStud2,
			Set gebuchtekurses, Set verweildauers, Set schülerinaktivzeitens,
			Set gebührens) {
		this.id = id;
		this.zahlungsArt = zahlungsArt;
		this.zahlungsWeise = zahlungsWeise;
		this.wannBeZahlen = wannBeZahlen;
		this.studiengebühr = studiengebühr;
		this.studBeginn1 = studBeginn1;
		this.studBeginn2 = studBeginn2;
		this.studBeginn3 = studBeginn3;
		this.vorStudBeginn1 = vorStudBeginn1;
		this.vorStudBeginn2 = vorStudBeginn2;
		this.rabattstring = rabattstring;
		this.bankeinzugAutomatik = bankeinzugAutomatik;
		this.inaktiv = inaktiv;
		this.studiengebühr2 = studiengebühr2;
		this.studiengebühr3 = studiengebühr3;
		this.vorStudiengebühr1 = vorStudiengebühr1;
		this.vorStudiengebühr2 = vorStudiengebühr2;
		this.kategorieStud1 = kategorieStud1;
		this.kategorieStud2 = kategorieStud2;
		this.kategorieStud3 = kategorieStud3;
		this.kategorieVorStud1 = kategorieVorStud1;
		this.kategorieVorStud2 = kategorieVorStud2;
		this.gebuchtekurses = gebuchtekurses;
		this.verweildauers = verweildauers;
		this.schülerinaktivzeitens = schülerinaktivzeitens;
		this.gebührens = gebührens;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getZahlungsArt() {
		return this.zahlungsArt;
	}

	public void setZahlungsArt(Integer zahlungsArt) {
		this.zahlungsArt = zahlungsArt;
	}

	public Integer getZahlungsWeise() {
		return this.zahlungsWeise;
	}

	public void setZahlungsWeise(Integer zahlungsWeise) {
		this.zahlungsWeise = zahlungsWeise;
	}

	public String getWannBeZahlen() {
		return this.wannBeZahlen;
	}

	public void setWannBeZahlen(String wannBeZahlen) {
		this.wannBeZahlen = wannBeZahlen;
	}

	public Double getStudiengebühr() {
		return this.studiengebühr;
	}

	public void setStudiengebühr(Double studiengebühr) {
		this.studiengebühr = studiengebühr;
	}

	public Date getStudBeginn1() {
		return this.studBeginn1;
	}

	public void setStudBeginn1(Date studBeginn1) {
		this.studBeginn1 = studBeginn1;
	}

	public Date getStudBeginn2() {
		return this.studBeginn2;
	}

	public void setStudBeginn2(Date studBeginn2) {
		this.studBeginn2 = studBeginn2;
	}

	public Date getStudBeginn3() {
		return this.studBeginn3;
	}

	public void setStudBeginn3(Date studBeginn3) {
		this.studBeginn3 = studBeginn3;
	}

	public Date getVorStudBeginn1() {
		return this.vorStudBeginn1;
	}

	public void setVorStudBeginn1(Date vorStudBeginn1) {
		this.vorStudBeginn1 = vorStudBeginn1;
	}

	public Date getVorStudBeginn2() {
		return this.vorStudBeginn2;
	}

	public void setVorStudBeginn2(Date vorStudBeginn2) {
		this.vorStudBeginn2 = vorStudBeginn2;
	}

	public String getRabattstring() {
		return this.rabattstring;
	}

	public void setRabattstring(String rabattstring) {
		this.rabattstring = rabattstring;
	}

	public Double getBankeinzugAutomatik() {
		return this.bankeinzugAutomatik;
	}

	public void setBankeinzugAutomatik(Double bankeinzugAutomatik) {
		this.bankeinzugAutomatik = bankeinzugAutomatik;
	}

	public Double getInaktiv() {
		return this.inaktiv;
	}

	public void setInaktiv(Double inaktiv) {
		this.inaktiv = inaktiv;
	}

	public Double getStudiengebühr2() {
		return this.studiengebühr2;
	}

	public void setStudiengebühr2(Double studiengebühr2) {
		this.studiengebühr2 = studiengebühr2;
	}

	public Double getStudiengebühr3() {
		return this.studiengebühr3;
	}

	public void setStudiengebühr3(Double studiengebühr3) {
		this.studiengebühr3 = studiengebühr3;
	}

	public Double getVorStudiengebühr1() {
		return this.vorStudiengebühr1;
	}

	public void setVorStudiengebühr1(Double vorStudiengebühr1) {
		this.vorStudiengebühr1 = vorStudiengebühr1;
	}

	public Double getVorStudiengebühr2() {
		return this.vorStudiengebühr2;
	}

	public void setVorStudiengebühr2(Double vorStudiengebühr2) {
		this.vorStudiengebühr2 = vorStudiengebühr2;
	}

	public Integer getKategorieStud1() {
		return this.kategorieStud1;
	}

	public void setKategorieStud1(Integer kategorieStud1) {
		this.kategorieStud1 = kategorieStud1;
	}

	public Integer getKategorieStud2() {
		return this.kategorieStud2;
	}

	public void setKategorieStud2(Integer kategorieStud2) {
		this.kategorieStud2 = kategorieStud2;
	}

	public Integer getKategorieStud3() {
		return this.kategorieStud3;
	}

	public void setKategorieStud3(Integer kategorieStud3) {
		this.kategorieStud3 = kategorieStud3;
	}

	public Integer getKategorieVorStud1() {
		return this.kategorieVorStud1;
	}

	public void setKategorieVorStud1(Integer kategorieVorStud1) {
		this.kategorieVorStud1 = kategorieVorStud1;
	}

	public Integer getKategorieVorStud2() {
		return this.kategorieVorStud2;
	}

	public void setKategorieVorStud2(Integer kategorieVorStud2) {
		this.kategorieVorStud2 = kategorieVorStud2;
	}

	public Set getGebuchtekurses() {
		return this.gebuchtekurses;
	}

	public void setGebuchtekurses(Set gebuchtekurses) {
		this.gebuchtekurses = gebuchtekurses;
	}

	public Set getVerweildauers() {
		return this.verweildauers;
	}

	public void setVerweildauers(Set verweildauers) {
		this.verweildauers = verweildauers;
	}

	public Set getSchülerinaktivzeitens() {
		return this.schülerinaktivzeitens;
	}

	public void setSchülerinaktivzeitens(Set schülerinaktivzeitens) {
		this.schülerinaktivzeitens = schülerinaktivzeitens;
	}

	public Set getGebührens() {
		return this.gebührens;
	}

	public void setGebührens(Set gebührens) {
		this.gebührens = gebührens;
	}

}
