// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * SchülerlisteId generated by hbm2java
 */
public class SchülerlisteId implements java.io.Serializable {

	private String kategorie;
	private String nachname;
	private String vorname;
	private String firma;
	private String kurs;
	private String typ;
	private Integer lehrer;
	private String straße;
	private String plz;
	private String ort;
	private String telefon;
	private String ersterWertVonKürzel;

	public SchülerlisteId() {
	}

	public SchülerlisteId(String kategorie, String nachname, String vorname,
			String firma, String kurs, String typ, Integer lehrer,
			String straße, String plz, String ort, String telefon,
			String ersterWertVonKürzel) {
		this.kategorie = kategorie;
		this.nachname = nachname;
		this.vorname = vorname;
		this.firma = firma;
		this.kurs = kurs;
		this.typ = typ;
		this.lehrer = lehrer;
		this.straße = straße;
		this.plz = plz;
		this.ort = ort;
		this.telefon = telefon;
		this.ersterWertVonKürzel = ersterWertVonKürzel;
	}

	public String getKategorie() {
		return this.kategorie;
	}

	public void setKategorie(String kategorie) {
		this.kategorie = kategorie;
	}

	public String getNachname() {
		return this.nachname;
	}

	public void setNachname(String nachname) {
		this.nachname = nachname;
	}

	public String getVorname() {
		return this.vorname;
	}

	public void setVorname(String vorname) {
		this.vorname = vorname;
	}

	public String getFirma() {
		return this.firma;
	}

	public void setFirma(String firma) {
		this.firma = firma;
	}

	public String getKurs() {
		return this.kurs;
	}

	public void setKurs(String kurs) {
		this.kurs = kurs;
	}

	public String getTyp() {
		return this.typ;
	}

	public void setTyp(String typ) {
		this.typ = typ;
	}

	public Integer getLehrer() {
		return this.lehrer;
	}

	public void setLehrer(Integer lehrer) {
		this.lehrer = lehrer;
	}

	public String getStraße() {
		return this.straße;
	}

	public void setStraße(String straße) {
		this.straße = straße;
	}

	public String getPlz() {
		return this.plz;
	}

	public void setPlz(String plz) {
		this.plz = plz;
	}

	public String getOrt() {
		return this.ort;
	}

	public void setOrt(String ort) {
		this.ort = ort;
	}

	public String getTelefon() {
		return this.telefon;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

	public String getErsterWertVonKürzel() {
		return this.ersterWertVonKürzel;
	}

	public void setErsterWertVonKürzel(String ersterWertVonKürzel) {
		this.ersterWertVonKürzel = ersterWertVonKürzel;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SchülerlisteId))
			return false;
		SchülerlisteId castOther = (SchülerlisteId) other;

		return ((this.getKategorie() == castOther.getKategorie()) || (this
				.getKategorie() != null && castOther.getKategorie() != null && this
				.getKategorie().equals(castOther.getKategorie())))
				&& ((this.getNachname() == castOther.getNachname()) || (this
						.getNachname() != null
						&& castOther.getNachname() != null && this
						.getNachname().equals(castOther.getNachname())))
				&& ((this.getVorname() == castOther.getVorname()) || (this
						.getVorname() != null && castOther.getVorname() != null && this
						.getVorname().equals(castOther.getVorname())))
				&& ((this.getFirma() == castOther.getFirma()) || (this
						.getFirma() != null && castOther.getFirma() != null && this
						.getFirma().equals(castOther.getFirma())))
				&& ((this.getKurs() == castOther.getKurs()) || (this.getKurs() != null
						&& castOther.getKurs() != null && this.getKurs()
						.equals(castOther.getKurs())))
				&& ((this.getTyp() == castOther.getTyp()) || (this.getTyp() != null
						&& castOther.getTyp() != null && this.getTyp().equals(
						castOther.getTyp())))
				&& ((this.getLehrer() == castOther.getLehrer()) || (this
						.getLehrer() != null && castOther.getLehrer() != null && this
						.getLehrer().equals(castOther.getLehrer())))
				&& ((this.getStraße() == castOther.getStraße()) || (this
						.getStraße() != null && castOther.getStraße() != null && this
						.getStraße().equals(castOther.getStraße())))
				&& ((this.getPlz() == castOther.getPlz()) || (this.getPlz() != null
						&& castOther.getPlz() != null && this.getPlz().equals(
						castOther.getPlz())))
				&& ((this.getOrt() == castOther.getOrt()) || (this.getOrt() != null
						&& castOther.getOrt() != null && this.getOrt().equals(
						castOther.getOrt())))
				&& ((this.getTelefon() == castOther.getTelefon()) || (this
						.getTelefon() != null && castOther.getTelefon() != null && this
						.getTelefon().equals(castOther.getTelefon())))
				&& ((this.getErsterWertVonKürzel() == castOther
						.getErsterWertVonKürzel()) || (this
						.getErsterWertVonKürzel() != null
						&& castOther.getErsterWertVonKürzel() != null && this
						.getErsterWertVonKürzel().equals(
								castOther.getErsterWertVonKürzel())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getKategorie() == null ? 0 : this.getKategorie().hashCode());
		result = 37 * result
				+ (getNachname() == null ? 0 : this.getNachname().hashCode());
		result = 37 * result
				+ (getVorname() == null ? 0 : this.getVorname().hashCode());
		result = 37 * result
				+ (getFirma() == null ? 0 : this.getFirma().hashCode());
		result = 37 * result
				+ (getKurs() == null ? 0 : this.getKurs().hashCode());
		result = 37 * result
				+ (getTyp() == null ? 0 : this.getTyp().hashCode());
		result = 37 * result
				+ (getLehrer() == null ? 0 : this.getLehrer().hashCode());
		result = 37 * result
				+ (getStraße() == null ? 0 : this.getStraße().hashCode());
		result = 37 * result
				+ (getPlz() == null ? 0 : this.getPlz().hashCode());
		result = 37 * result
				+ (getOrt() == null ? 0 : this.getOrt().hashCode());
		result = 37 * result
				+ (getTelefon() == null ? 0 : this.getTelefon().hashCode());
		result = 37
				* result
				+ (getErsterWertVonKürzel() == null ? 0 : this
						.getErsterWertVonKürzel().hashCode());
		return result;
	}

}
