// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SchülerinaktivzeitenId generated by hbm2java
 */
public class SchülerinaktivzeitenId implements java.io.Serializable {

	private Integer id;
	private Date inaktivBis;
	private Date inaktivVon;
	private Integer schülerId;

	public SchülerinaktivzeitenId() {
	}

	public SchülerinaktivzeitenId(Integer id, Date inaktivBis, Date inaktivVon,
			Integer schülerId) {
		this.id = id;
		this.inaktivBis = inaktivBis;
		this.inaktivVon = inaktivVon;
		this.schülerId = schülerId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getInaktivBis() {
		return this.inaktivBis;
	}

	public void setInaktivBis(Date inaktivBis) {
		this.inaktivBis = inaktivBis;
	}

	public Date getInaktivVon() {
		return this.inaktivVon;
	}

	public void setInaktivVon(Date inaktivVon) {
		this.inaktivVon = inaktivVon;
	}

	public Integer getSchülerId() {
		return this.schülerId;
	}

	public void setSchülerId(Integer schülerId) {
		this.schülerId = schülerId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SchülerinaktivzeitenId))
			return false;
		SchülerinaktivzeitenId castOther = (SchülerinaktivzeitenId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getInaktivBis() == castOther.getInaktivBis()) || (this
						.getInaktivBis() != null
						&& castOther.getInaktivBis() != null && this
						.getInaktivBis().equals(castOther.getInaktivBis())))
				&& ((this.getInaktivVon() == castOther.getInaktivVon()) || (this
						.getInaktivVon() != null
						&& castOther.getInaktivVon() != null && this
						.getInaktivVon().equals(castOther.getInaktivVon())))
				&& ((this.getSchülerId() == castOther.getSchülerId()) || (this
						.getSchülerId() != null
						&& castOther.getSchülerId() != null && this
						.getSchülerId().equals(castOther.getSchülerId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getInaktivBis() == null ? 0 : this.getInaktivBis()
						.hashCode());
		result = 37
				* result
				+ (getInaktivVon() == null ? 0 : this.getInaktivVon()
						.hashCode());
		result = 37 * result
				+ (getSchülerId() == null ? 0 : this.getSchülerId().hashCode());
		return result;
	}

}
