// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Schülerliste generated by hbm2java
 */
public class Schülerliste implements java.io.Serializable {

	private SchülerlisteId id;

	public Schülerliste() {
	}

	public Schülerliste(SchülerlisteId id) {
		this.id = id;
	}

	public SchülerlisteId getId() {
		return this.id;
	}

	public void setId(SchülerlisteId id) {
		this.id = id;
	}

}
