// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Schülerinaktivzeiten generated by hbm2java
 */
public class Schülerinaktivzeiten implements java.io.Serializable {

	private SchülerinaktivzeitenId id;
	private Schülerinformationen schülerinformationen;

	public Schülerinaktivzeiten() {
	}

	public Schülerinaktivzeiten(SchülerinaktivzeitenId id) {
		this.id = id;
	}

	public Schülerinaktivzeiten(SchülerinaktivzeitenId id,
			Schülerinformationen schülerinformationen) {
		this.id = id;
		this.schülerinformationen = schülerinformationen;
	}

	public SchülerinaktivzeitenId getId() {
		return this.id;
	}

	public void setId(SchülerinaktivzeitenId id) {
		this.id = id;
	}

	public Schülerinformationen getSchülerinformationen() {
		return this.schülerinformationen;
	}

	public void setSchülerinformationen(
			Schülerinformationen schülerinformationen) {
		this.schülerinformationen = schülerinformationen;
	}

}
