// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Semester generated by hbm2java
 */
public class Semester implements java.io.Serializable {

	private int id;
	private String bezeichnung;
	private Date von;
	private Date bis;
	private Short jahreszeit;

	public Semester() {
	}

	public Semester(int id) {
		this.id = id;
	}

	public Semester(int id, String bezeichnung, Date von, Date bis,
			Short jahreszeit) {
		this.id = id;
		this.bezeichnung = bezeichnung;
		this.von = von;
		this.bis = bis;
		this.jahreszeit = jahreszeit;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getBezeichnung() {
		return this.bezeichnung;
	}

	public void setBezeichnung(String bezeichnung) {
		this.bezeichnung = bezeichnung;
	}

	public Date getVon() {
		return this.von;
	}

	public void setVon(Date von) {
		this.von = von;
	}

	public Date getBis() {
		return this.bis;
	}

	public void setBis(Date bis) {
		this.bis = bis;
	}

	public Short getJahreszeit() {
		return this.jahreszeit;
	}

	public void setJahreszeit(Short jahreszeit) {
		this.jahreszeit = jahreszeit;
	}

}
