// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Sonstigehonorare generated by hbm2java
 */
public class Sonstigehonorare implements java.io.Serializable {

	private int id;
	private Kategorien kategorien;
	private Double betrag;
	private Integer lehrer;
	private String bezeichnung;
	private Short status;
	private Date von;
	private Date bis;
	private Float wochenstunden;

	public Sonstigehonorare() {
	}

	public Sonstigehonorare(int id) {
		this.id = id;
	}

	public Sonstigehonorare(int id, Kategorien kategorien, Double betrag,
			Integer lehrer, String bezeichnung, Short status, Date von,
			Date bis, Float wochenstunden) {
		this.id = id;
		this.kategorien = kategorien;
		this.betrag = betrag;
		this.lehrer = lehrer;
		this.bezeichnung = bezeichnung;
		this.status = status;
		this.von = von;
		this.bis = bis;
		this.wochenstunden = wochenstunden;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Kategorien getKategorien() {
		return this.kategorien;
	}

	public void setKategorien(Kategorien kategorien) {
		this.kategorien = kategorien;
	}

	public Double getBetrag() {
		return this.betrag;
	}

	public void setBetrag(Double betrag) {
		this.betrag = betrag;
	}

	public Integer getLehrer() {
		return this.lehrer;
	}

	public void setLehrer(Integer lehrer) {
		this.lehrer = lehrer;
	}

	public String getBezeichnung() {
		return this.bezeichnung;
	}

	public void setBezeichnung(String bezeichnung) {
		this.bezeichnung = bezeichnung;
	}

	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public Date getVon() {
		return this.von;
	}

	public void setVon(Date von) {
		this.von = von;
	}

	public Date getBis() {
		return this.bis;
	}

	public void setBis(Date bis) {
		this.bis = bis;
	}

	public Float getWochenstunden() {
		return this.wochenstunden;
	}

	public void setWochenstunden(Float wochenstunden) {
		this.wochenstunden = wochenstunden;
	}

}
