// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Sql generated by hbm2java
 */
public class Sql implements java.io.Serializable {

	private int id;
	private String name;
	private String text;
	private Boolean action;
	private Boolean data;

	public Sql() {
	}

	public Sql(int id) {
		this.id = id;
	}

	public Sql(int id, String name, String text, Boolean action, Boolean data) {
		this.id = id;
		this.name = name;
		this.text = text;
		this.action = action;
		this.data = data;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Boolean getAction() {
		return this.action;
	}

	public void setAction(Boolean action) {
		this.action = action;
	}

	public Boolean getData() {
		return this.data;
	}

	public void setData(Boolean data) {
		this.data = data;
	}

}
