// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * StandardhonorareId generated by hbm2java
 */
public class StandardhonorareId implements java.io.Serializable {

	private Short anzahl;
	private Double gebühr;
	private Double honorar;

	public StandardhonorareId() {
	}

	public StandardhonorareId(Short anzahl, Double gebühr, Double honorar) {
		this.anzahl = anzahl;
		this.gebühr = gebühr;
		this.honorar = honorar;
	}

	public Short getAnzahl() {
		return this.anzahl;
	}

	public void setAnzahl(Short anzahl) {
		this.anzahl = anzahl;
	}

	public Double getGebühr() {
		return this.gebühr;
	}

	public void setGebühr(Double gebühr) {
		this.gebühr = gebühr;
	}

	public Double getHonorar() {
		return this.honorar;
	}

	public void setHonorar(Double honorar) {
		this.honorar = honorar;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StandardhonorareId))
			return false;
		StandardhonorareId castOther = (StandardhonorareId) other;

		return ((this.getAnzahl() == castOther.getAnzahl()) || (this
				.getAnzahl() != null && castOther.getAnzahl() != null && this
				.getAnzahl().equals(castOther.getAnzahl())))
				&& ((this.getGebühr() == castOther.getGebühr()) || (this
						.getGebühr() != null && castOther.getGebühr() != null && this
						.getGebühr().equals(castOther.getGebühr())))
				&& ((this.getHonorar() == castOther.getHonorar()) || (this
						.getHonorar() != null && castOther.getHonorar() != null && this
						.getHonorar().equals(castOther.getHonorar())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAnzahl() == null ? 0 : this.getAnzahl().hashCode());
		result = 37 * result
				+ (getGebühr() == null ? 0 : this.getGebühr().hashCode());
		result = 37 * result
				+ (getHonorar() == null ? 0 : this.getHonorar().hashCode());
		return result;
	}

}
