// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Standardhonorare generated by hbm2java
 */
public class Standardhonorare implements java.io.Serializable {

	private StandardhonorareId id;

	public Standardhonorare() {
	}

	public Standardhonorare(StandardhonorareId id) {
		this.id = id;
	}

	public StandardhonorareId getId() {
		return this.id;
	}

	public void setId(StandardhonorareId id) {
		this.id = id;
	}

}
