// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TarifbeträgeId generated by hbm2java
 */
public class TarifbeträgeId implements java.io.Serializable {

	private Integer tarifId;
	private Integer teilnehmer;
	private Date gültigAb;
	private Double honorar;
	private Double honorar3;
	private Double gebühr;
	private Double honorar2;
	private Double gebührErmässigt;
	private Double gebührErmässigt2;

	public TarifbeträgeId() {
	}

	public TarifbeträgeId(Integer tarifId, Integer teilnehmer, Date gültigAb,
			Double honorar, Double honorar3, Double gebühr, Double honorar2,
			Double gebührErmässigt, Double gebührErmässigt2) {
		this.tarifId = tarifId;
		this.teilnehmer = teilnehmer;
		this.gültigAb = gültigAb;
		this.honorar = honorar;
		this.honorar3 = honorar3;
		this.gebühr = gebühr;
		this.honorar2 = honorar2;
		this.gebührErmässigt = gebührErmässigt;
		this.gebührErmässigt2 = gebührErmässigt2;
	}

	public Integer getTarifId() {
		return this.tarifId;
	}

	public void setTarifId(Integer tarifId) {
		this.tarifId = tarifId;
	}

	public Integer getTeilnehmer() {
		return this.teilnehmer;
	}

	public void setTeilnehmer(Integer teilnehmer) {
		this.teilnehmer = teilnehmer;
	}

	public Date getGültigAb() {
		return this.gültigAb;
	}

	public void setGültigAb(Date gültigAb) {
		this.gültigAb = gültigAb;
	}

	public Double getHonorar() {
		return this.honorar;
	}

	public void setHonorar(Double honorar) {
		this.honorar = honorar;
	}

	public Double getHonorar3() {
		return this.honorar3;
	}

	public void setHonorar3(Double honorar3) {
		this.honorar3 = honorar3;
	}

	public Double getGebühr() {
		return this.gebühr;
	}

	public void setGebühr(Double gebühr) {
		this.gebühr = gebühr;
	}

	public Double getHonorar2() {
		return this.honorar2;
	}

	public void setHonorar2(Double honorar2) {
		this.honorar2 = honorar2;
	}

	public Double getGebührErmässigt() {
		return this.gebührErmässigt;
	}

	public void setGebührErmässigt(Double gebührErmässigt) {
		this.gebührErmässigt = gebührErmässigt;
	}

	public Double getGebührErmässigt2() {
		return this.gebührErmässigt2;
	}

	public void setGebührErmässigt2(Double gebührErmässigt2) {
		this.gebührErmässigt2 = gebührErmässigt2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TarifbeträgeId))
			return false;
		TarifbeträgeId castOther = (TarifbeträgeId) other;

		return ((this.getTarifId() == castOther.getTarifId()) || (this
				.getTarifId() != null && castOther.getTarifId() != null && this
				.getTarifId().equals(castOther.getTarifId())))
				&& ((this.getTeilnehmer() == castOther.getTeilnehmer()) || (this
						.getTeilnehmer() != null
						&& castOther.getTeilnehmer() != null && this
						.getTeilnehmer().equals(castOther.getTeilnehmer())))
				&& ((this.getGültigAb() == castOther.getGültigAb()) || (this
						.getGültigAb() != null
						&& castOther.getGültigAb() != null && this
						.getGültigAb().equals(castOther.getGültigAb())))
				&& ((this.getHonorar() == castOther.getHonorar()) || (this
						.getHonorar() != null && castOther.getHonorar() != null && this
						.getHonorar().equals(castOther.getHonorar())))
				&& ((this.getHonorar3() == castOther.getHonorar3()) || (this
						.getHonorar3() != null
						&& castOther.getHonorar3() != null && this
						.getHonorar3().equals(castOther.getHonorar3())))
				&& ((this.getGebühr() == castOther.getGebühr()) || (this
						.getGebühr() != null && castOther.getGebühr() != null && this
						.getGebühr().equals(castOther.getGebühr())))
				&& ((this.getHonorar2() == castOther.getHonorar2()) || (this
						.getHonorar2() != null
						&& castOther.getHonorar2() != null && this
						.getHonorar2().equals(castOther.getHonorar2())))
				&& ((this.getGebührErmässigt() == castOther
						.getGebührErmässigt()) || (this.getGebührErmässigt() != null
						&& castOther.getGebührErmässigt() != null && this
						.getGebührErmässigt().equals(
								castOther.getGebührErmässigt())))
				&& ((this.getGebührErmässigt2() == castOther
						.getGebührErmässigt2()) || (this.getGebührErmässigt2() != null
						&& castOther.getGebührErmässigt2() != null && this
						.getGebührErmässigt2().equals(
								castOther.getGebührErmässigt2())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTarifId() == null ? 0 : this.getTarifId().hashCode());
		result = 37
				* result
				+ (getTeilnehmer() == null ? 0 : this.getTeilnehmer()
						.hashCode());
		result = 37 * result
				+ (getGültigAb() == null ? 0 : this.getGültigAb().hashCode());
		result = 37 * result
				+ (getHonorar() == null ? 0 : this.getHonorar().hashCode());
		result = 37 * result
				+ (getHonorar3() == null ? 0 : this.getHonorar3().hashCode());
		result = 37 * result
				+ (getGebühr() == null ? 0 : this.getGebühr().hashCode());
		result = 37 * result
				+ (getHonorar2() == null ? 0 : this.getHonorar2().hashCode());
		result = 37
				* result
				+ (getGebührErmässigt() == null ? 0 : this.getGebührErmässigt()
						.hashCode());
		result = 37
				* result
				+ (getGebührErmässigt2() == null ? 0 : this
						.getGebührErmässigt2().hashCode());
		return result;
	}

}
