// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Tarifbeträge generated by hbm2java
 */
public class Tarifbeträge implements java.io.Serializable {

	private TarifbeträgeId id;
	private Tarif tarif;

	public Tarifbeträge() {
	}

	public Tarifbeträge(TarifbeträgeId id) {
		this.id = id;
	}

	public Tarifbeträge(TarifbeträgeId id, Tarif tarif) {
		this.id = id;
		this.tarif = tarif;
	}

	public TarifbeträgeId getId() {
		return this.id;
	}

	public void setId(TarifbeträgeId id) {
		this.id = id;
	}

	public Tarif getTarif() {
		return this.tarif;
	}

	public void setTarif(Tarif tarif) {
		this.tarif = tarif;
	}

}
