// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tarif generated by hbm2java
 */
public class Tarif implements java.io.Serializable {

	private int id;
	private String bez;
	private Integer unterrichtstyp;
	private String typ;
	private Set tarifbeträges = new HashSet(0);

	public Tarif() {
	}

	public Tarif(int id) {
		this.id = id;
	}

	public Tarif(int id, String bez, Integer unterrichtstyp, String typ,
			Set tarifbeträges) {
		this.id = id;
		this.bez = bez;
		this.unterrichtstyp = unterrichtstyp;
		this.typ = typ;
		this.tarifbeträges = tarifbeträges;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getBez() {
		return this.bez;
	}

	public void setBez(String bez) {
		this.bez = bez;
	}

	public Integer getUnterrichtstyp() {
		return this.unterrichtstyp;
	}

	public void setUnterrichtstyp(Integer unterrichtstyp) {
		this.unterrichtstyp = unterrichtstyp;
	}

	public String getTyp() {
		return this.typ;
	}

	public void setTyp(String typ) {
		this.typ = typ;
	}

	public Set getTarifbeträges() {
		return this.tarifbeträges;
	}

	public void setTarifbeträges(Set tarifbeträges) {
		this.tarifbeträges = tarifbeträges;
	}

}
