// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * THonorarabrechnungenpos generated by hbm2java
 */
public class THonorarabrechnungenpos implements java.io.Serializable {

	private int id;
	private Integer abrechnungId;
	private String monat;
	private String schüler;
	private String unterricht;
	private Double betrag;
	private String kategorie;

	public THonorarabrechnungenpos() {
	}

	public THonorarabrechnungenpos(int id) {
		this.id = id;
	}

	public THonorarabrechnungenpos(int id, Integer abrechnungId, String monat,
			String schüler, String unterricht, Double betrag, String kategorie) {
		this.id = id;
		this.abrechnungId = abrechnungId;
		this.monat = monat;
		this.schüler = schüler;
		this.unterricht = unterricht;
		this.betrag = betrag;
		this.kategorie = kategorie;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getAbrechnungId() {
		return this.abrechnungId;
	}

	public void setAbrechnungId(Integer abrechnungId) {
		this.abrechnungId = abrechnungId;
	}

	public String getMonat() {
		return this.monat;
	}

	public void setMonat(String monat) {
		this.monat = monat;
	}

	public String getSchüler() {
		return this.schüler;
	}

	public void setSchüler(String schüler) {
		this.schüler = schüler;
	}

	public String getUnterricht() {
		return this.unterricht;
	}

	public void setUnterricht(String unterricht) {
		this.unterricht = unterricht;
	}

	public Double getBetrag() {
		return this.betrag;
	}

	public void setBetrag(Double betrag) {
		this.betrag = betrag;
	}

	public String getKategorie() {
		return this.kategorie;
	}

	public void setKategorie(String kategorie) {
		this.kategorie = kategorie;
	}

}
