// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Turnus generated by hbm2java
 */
public class Turnus implements java.io.Serializable {

	private int id;
	private String name;
	private Set kurses = new HashSet(0);

	public Turnus() {
	}

	public Turnus(int id) {
		this.id = id;
	}

	public Turnus(int id, String name, Set kurses) {
		this.id = id;
		this.name = name;
		this.kurses = kurses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getKurses() {
		return this.kurses;
	}

	public void setKurses(Set kurses) {
		this.kurses = kurses;
	}

}
