// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Unterrichtstypen generated by hbm2java
 */
public class Unterrichtstypen implements java.io.Serializable {

	private int id;
	private String name;
	private Boolean geschützt;
	private Boolean instrument;
	private Boolean lehrer;
	private Boolean einzel;

	public Unterrichtstypen() {
	}

	public Unterrichtstypen(int id) {
		this.id = id;
	}

	public Unterrichtstypen(int id, String name, Boolean geschützt,
			Boolean instrument, Boolean lehrer, Boolean einzel) {
		this.id = id;
		this.name = name;
		this.geschützt = geschützt;
		this.instrument = instrument;
		this.lehrer = lehrer;
		this.einzel = einzel;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getGeschützt() {
		return this.geschützt;
	}

	public void setGeschützt(Boolean geschützt) {
		this.geschützt = geschützt;
	}

	public Boolean getInstrument() {
		return this.instrument;
	}

	public void setInstrument(Boolean instrument) {
		this.instrument = instrument;
	}

	public Boolean getLehrer() {
		return this.lehrer;
	}

	public void setLehrer(Boolean lehrer) {
		this.lehrer = lehrer;
	}

	public Boolean getEinzel() {
		return this.einzel;
	}

	public void setEinzel(Boolean einzel) {
		this.einzel = einzel;
	}

}
