// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Unterrichtsvertraege generated by hbm2java
 */
public class Unterrichtsvertraege implements java.io.Serializable {

	private int id;
	private Adressen adressen;
	private Integer status;
	private String anrede;
	private String vorname;
	private String nachname;
	private String straße;
	private String plz;
	private String ort;
	private String telPrivat;
	private String telDienstl;
	private String telMobil;
	private String email;
	private String gebDat;
	private Integer anmeldungFuer;
	private String anmeldungVorname;
	private String anmeldungNachname;
	private String anmeldungGebDat;
	private Integer einschreibeGebühr;
	private Integer kursId;
	private Integer instrumentId;
	private Integer kategorie;
	private String rabattString;
	private Double egebühr;
	private Double ehonorar1;
	private Double ehonorar2;
	private Integer zahlungsArt;
	private Integer zahlungsWeise;
	private String kontoInhaber;
	private String kontoNr;
	private String bank;
	private String blz;
	private Date ersteStunde;
	private Date datumErstellung;
	private Date datumVertrag;
	private Integer benutzer;
	private Integer beginntTyp;
	private String beginntParam;
	private String rabattText;
	private Double gebühr;
	private String weitereKurse;
	private String geschwister;
	private String bemerkungen;

	public Unterrichtsvertraege() {
	}

	public Unterrichtsvertraege(int id) {
		this.id = id;
	}

	public Unterrichtsvertraege(int id, Adressen adressen, Integer status,
			String anrede, String vorname, String nachname, String straße,
			String plz, String ort, String telPrivat, String telDienstl,
			String telMobil, String email, String gebDat,
			Integer anmeldungFuer, String anmeldungVorname,
			String anmeldungNachname, String anmeldungGebDat,
			Integer einschreibeGebühr, Integer kursId, Integer instrumentId,
			Integer kategorie, String rabattString, Double egebühr,
			Double ehonorar1, Double ehonorar2, Integer zahlungsArt,
			Integer zahlungsWeise, String kontoInhaber, String kontoNr,
			String bank, String blz, Date ersteStunde, Date datumErstellung,
			Date datumVertrag, Integer benutzer, Integer beginntTyp,
			String beginntParam, String rabattText, Double gebühr,
			String weitereKurse, String geschwister, String bemerkungen) {
		this.id = id;
		this.adressen = adressen;
		this.status = status;
		this.anrede = anrede;
		this.vorname = vorname;
		this.nachname = nachname;
		this.straße = straße;
		this.plz = plz;
		this.ort = ort;
		this.telPrivat = telPrivat;
		this.telDienstl = telDienstl;
		this.telMobil = telMobil;
		this.email = email;
		this.gebDat = gebDat;
		this.anmeldungFuer = anmeldungFuer;
		this.anmeldungVorname = anmeldungVorname;
		this.anmeldungNachname = anmeldungNachname;
		this.anmeldungGebDat = anmeldungGebDat;
		this.einschreibeGebühr = einschreibeGebühr;
		this.kursId = kursId;
		this.instrumentId = instrumentId;
		this.kategorie = kategorie;
		this.rabattString = rabattString;
		this.egebühr = egebühr;
		this.ehonorar1 = ehonorar1;
		this.ehonorar2 = ehonorar2;
		this.zahlungsArt = zahlungsArt;
		this.zahlungsWeise = zahlungsWeise;
		this.kontoInhaber = kontoInhaber;
		this.kontoNr = kontoNr;
		this.bank = bank;
		this.blz = blz;
		this.ersteStunde = ersteStunde;
		this.datumErstellung = datumErstellung;
		this.datumVertrag = datumVertrag;
		this.benutzer = benutzer;
		this.beginntTyp = beginntTyp;
		this.beginntParam = beginntParam;
		this.rabattText = rabattText;
		this.gebühr = gebühr;
		this.weitereKurse = weitereKurse;
		this.geschwister = geschwister;
		this.bemerkungen = bemerkungen;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Adressen getAdressen() {
		return this.adressen;
	}

	public void setAdressen(Adressen adressen) {
		this.adressen = adressen;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getAnrede() {
		return this.anrede;
	}

	public void setAnrede(String anrede) {
		this.anrede = anrede;
	}

	public String getVorname() {
		return this.vorname;
	}

	public void setVorname(String vorname) {
		this.vorname = vorname;
	}

	public String getNachname() {
		return this.nachname;
	}

	public void setNachname(String nachname) {
		this.nachname = nachname;
	}

	public String getStraße() {
		return this.straße;
	}

	public void setStraße(String straße) {
		this.straße = straße;
	}

	public String getPlz() {
		return this.plz;
	}

	public void setPlz(String plz) {
		this.plz = plz;
	}

	public String getOrt() {
		return this.ort;
	}

	public void setOrt(String ort) {
		this.ort = ort;
	}

	public String getTelPrivat() {
		return this.telPrivat;
	}

	public void setTelPrivat(String telPrivat) {
		this.telPrivat = telPrivat;
	}

	public String getTelDienstl() {
		return this.telDienstl;
	}

	public void setTelDienstl(String telDienstl) {
		this.telDienstl = telDienstl;
	}

	public String getTelMobil() {
		return this.telMobil;
	}

	public void setTelMobil(String telMobil) {
		this.telMobil = telMobil;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getGebDat() {
		return this.gebDat;
	}

	public void setGebDat(String gebDat) {
		this.gebDat = gebDat;
	}

	public Integer getAnmeldungFuer() {
		return this.anmeldungFuer;
	}

	public void setAnmeldungFuer(Integer anmeldungFuer) {
		this.anmeldungFuer = anmeldungFuer;
	}

	public String getAnmeldungVorname() {
		return this.anmeldungVorname;
	}

	public void setAnmeldungVorname(String anmeldungVorname) {
		this.anmeldungVorname = anmeldungVorname;
	}

	public String getAnmeldungNachname() {
		return this.anmeldungNachname;
	}

	public void setAnmeldungNachname(String anmeldungNachname) {
		this.anmeldungNachname = anmeldungNachname;
	}

	public String getAnmeldungGebDat() {
		return this.anmeldungGebDat;
	}

	public void setAnmeldungGebDat(String anmeldungGebDat) {
		this.anmeldungGebDat = anmeldungGebDat;
	}

	public Integer getEinschreibeGebühr() {
		return this.einschreibeGebühr;
	}

	public void setEinschreibeGebühr(Integer einschreibeGebühr) {
		this.einschreibeGebühr = einschreibeGebühr;
	}

	public Integer getKursId() {
		return this.kursId;
	}

	public void setKursId(Integer kursId) {
		this.kursId = kursId;
	}

	public Integer getInstrumentId() {
		return this.instrumentId;
	}

	public void setInstrumentId(Integer instrumentId) {
		this.instrumentId = instrumentId;
	}

	public Integer getKategorie() {
		return this.kategorie;
	}

	public void setKategorie(Integer kategorie) {
		this.kategorie = kategorie;
	}

	public String getRabattString() {
		return this.rabattString;
	}

	public void setRabattString(String rabattString) {
		this.rabattString = rabattString;
	}

	public Double getEgebühr() {
		return this.egebühr;
	}

	public void setEgebühr(Double egebühr) {
		this.egebühr = egebühr;
	}

	public Double getEhonorar1() {
		return this.ehonorar1;
	}

	public void setEhonorar1(Double ehonorar1) {
		this.ehonorar1 = ehonorar1;
	}

	public Double getEhonorar2() {
		return this.ehonorar2;
	}

	public void setEhonorar2(Double ehonorar2) {
		this.ehonorar2 = ehonorar2;
	}

	public Integer getZahlungsArt() {
		return this.zahlungsArt;
	}

	public void setZahlungsArt(Integer zahlungsArt) {
		this.zahlungsArt = zahlungsArt;
	}

	public Integer getZahlungsWeise() {
		return this.zahlungsWeise;
	}

	public void setZahlungsWeise(Integer zahlungsWeise) {
		this.zahlungsWeise = zahlungsWeise;
	}

	public String getKontoInhaber() {
		return this.kontoInhaber;
	}

	public void setKontoInhaber(String kontoInhaber) {
		this.kontoInhaber = kontoInhaber;
	}

	public String getKontoNr() {
		return this.kontoNr;
	}

	public void setKontoNr(String kontoNr) {
		this.kontoNr = kontoNr;
	}

	public String getBank() {
		return this.bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	public String getBlz() {
		return this.blz;
	}

	public void setBlz(String blz) {
		this.blz = blz;
	}

	public Date getErsteStunde() {
		return this.ersteStunde;
	}

	public void setErsteStunde(Date ersteStunde) {
		this.ersteStunde = ersteStunde;
	}

	public Date getDatumErstellung() {
		return this.datumErstellung;
	}

	public void setDatumErstellung(Date datumErstellung) {
		this.datumErstellung = datumErstellung;
	}

	public Date getDatumVertrag() {
		return this.datumVertrag;
	}

	public void setDatumVertrag(Date datumVertrag) {
		this.datumVertrag = datumVertrag;
	}

	public Integer getBenutzer() {
		return this.benutzer;
	}

	public void setBenutzer(Integer benutzer) {
		this.benutzer = benutzer;
	}

	public Integer getBeginntTyp() {
		return this.beginntTyp;
	}

	public void setBeginntTyp(Integer beginntTyp) {
		this.beginntTyp = beginntTyp;
	}

	public String getBeginntParam() {
		return this.beginntParam;
	}

	public void setBeginntParam(String beginntParam) {
		this.beginntParam = beginntParam;
	}

	public String getRabattText() {
		return this.rabattText;
	}

	public void setRabattText(String rabattText) {
		this.rabattText = rabattText;
	}

	public Double getGebühr() {
		return this.gebühr;
	}

	public void setGebühr(Double gebühr) {
		this.gebühr = gebühr;
	}

	public String getWeitereKurse() {
		return this.weitereKurse;
	}

	public void setWeitereKurse(String weitereKurse) {
		this.weitereKurse = weitereKurse;
	}

	public String getGeschwister() {
		return this.geschwister;
	}

	public void setGeschwister(String geschwister) {
		this.geschwister = geschwister;
	}

	public String getBemerkungen() {
		return this.bemerkungen;
	}

	public void setBemerkungen(String bemerkungen) {
		this.bemerkungen = bemerkungen;
	}

}
