// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Verweildauer generated by hbm2java
 */
public class Verweildauer implements java.io.Serializable {

	private int id;
	private Kurse kurse;
	private Schülerinformationen schülerinformationen;
	private Integer anzahlWochen;
	private Integer lehrerId;

	public Verweildauer() {
	}

	public Verweildauer(int id) {
		this.id = id;
	}

	public Verweildauer(int id, Kurse kurse,
			Schülerinformationen schülerinformationen, Integer anzahlWochen,
			Integer lehrerId) {
		this.id = id;
		this.kurse = kurse;
		this.schülerinformationen = schülerinformationen;
		this.anzahlWochen = anzahlWochen;
		this.lehrerId = lehrerId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Kurse getKurse() {
		return this.kurse;
	}

	public void setKurse(Kurse kurse) {
		this.kurse = kurse;
	}

	public Schülerinformationen getSchülerinformationen() {
		return this.schülerinformationen;
	}

	public void setSchülerinformationen(
			Schülerinformationen schülerinformationen) {
		this.schülerinformationen = schülerinformationen;
	}

	public Integer getAnzahlWochen() {
		return this.anzahlWochen;
	}

	public void setAnzahlWochen(Integer anzahlWochen) {
		this.anzahlWochen = anzahlWochen;
	}

	public Integer getLehrerId() {
		return this.lehrerId;
	}

	public void setLehrerId(Integer lehrerId) {
		this.lehrerId = lehrerId;
	}

}
