// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Wochenstunden generated by hbm2java
 */
public class Wochenstunden implements java.io.Serializable {

	private int id;
	private Integer kategorie;
	private Double stunden;
	private Integer lehrer;

	public Wochenstunden() {
	}

	public Wochenstunden(int id) {
		this.id = id;
	}

	public Wochenstunden(int id, Integer kategorie, Double stunden,
			Integer lehrer) {
		this.id = id;
		this.kategorie = kategorie;
		this.stunden = stunden;
		this.lehrer = lehrer;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getKategorie() {
		return this.kategorie;
	}

	public void setKategorie(Integer kategorie) {
		this.kategorie = kategorie;
	}

	public Double getStunden() {
		return this.stunden;
	}

	public void setStunden(Double stunden) {
		this.stunden = stunden;
	}

	public Integer getLehrer() {
		return this.lehrer;
	}

	public void setLehrer(Integer lehrer) {
		this.lehrer = lehrer;
	}

}
