// default package
// Generated Dec 28, 2013 6:02:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Zahlungsarten generated by hbm2java
 */
public class Zahlungsarten implements java.io.Serializable {

	private int id;
	private String name;
	private Boolean geschützt;
	private Set gebührens = new HashSet(0);

	public Zahlungsarten() {
	}

	public Zahlungsarten(int id) {
		this.id = id;
	}

	public Zahlungsarten(int id, String name, Boolean geschützt, Set gebührens) {
		this.id = id;
		this.name = name;
		this.geschützt = geschützt;
		this.gebührens = gebührens;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getGeschützt() {
		return this.geschützt;
	}

	public void setGeschützt(Boolean geschützt) {
		this.geschützt = geschützt;
	}

	public Set getGebührens() {
		return this.gebührens;
	}

	public void setGebührens(Set gebührens) {
		this.gebührens = gebührens;
	}

}
